"use client";

import { useState } from "react";
import { useTranslations } from "next-intl";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { toast } from "sonner";
import { useRouter } from "next/navigation";
import { createUser } from "@/lib/actions/user-management";

interface RoleOption {
  name: string;
  displayName: string;
  level: number;
}

export default function AddUserDialog({ availableRoles }: { availableRoles: RoleOption[] }) {
  const t = useTranslations("admin.users");
  const tCommon = useTranslations("common");
  const router = useRouter();

  const [open, setOpen] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [username, setUsername] = useState("");
  const [email, setEmail] = useState("");
  const [name, setName] = useState("");
  const [className, setClassName] = useState("");
  const [role, setRole] = useState("student");
  const [password, setPassword] = useState("");

  const builtinRoleLabels: Record<string, string> = {
    student: t("roleOptions.student"),
    instructor: t("roleOptions.instructor"),
    admin: t("roleOptions.admin"),
  };

  function resetFormState() {
    setUsername("");
    setEmail("");
    setName("");
    setClassName("");
    setRole("student");
    setPassword("");
  }

  async function handleOpenChange(nextOpen: boolean) {
    setOpen(nextOpen);

    if (!nextOpen) {
      resetFormState();
    }
  }

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    setIsLoading(true);

    try {
      const result = await createUser({ username, email, name, className, role, password });
      if (result.success) {
        router.refresh();
        await handleOpenChange(false);
        toast.success(t("createSuccess"));
      } else {
        toast.error(t(result.error));
      }
    } catch {
      toast.error(tCommon("error"));
    } finally {
      setIsLoading(false);
    }
  }

  return (
    <Dialog open={open} onOpenChange={handleOpenChange}>
      <DialogTrigger render={<Button>{t("addUser")}</Button>} />
      <DialogContent className="sm:max-w-[425px]">
        <form onSubmit={handleSubmit} className="space-y-4">
            <DialogHeader>
              <DialogTitle>{t("addUser")}</DialogTitle>
              <DialogDescription>{t("autoGeneratedPasswordNotice")}</DialogDescription>
            </DialogHeader>
            <div className="space-y-2">
              <Label htmlFor="new-username">{t("table.username")}</Label>
              <Input id="new-username" value={username} onChange={e => setUsername(e.target.value)} required />
            </div>
            <div className="space-y-2">
              <Label htmlFor="new-name">{t("table.name")}</Label>
              <Input id="new-name" value={name} onChange={e => setName(e.target.value)} required />
            </div>
            <div className="space-y-2">
              <Label htmlFor="new-className">{tCommon("class")}</Label>
              <Input id="new-className" value={className} onChange={e => setClassName(e.target.value)} />
            </div>
            <div className="space-y-2">
              <Label htmlFor="new-email">{t("table.email")} ({tCommon("optional")})</Label>
              <Input id="new-email" type="email" value={email} onChange={e => setEmail(e.target.value)} />
            </div>
            <div className="space-y-2">
              <Label htmlFor="new-role">{t("table.role")}</Label>
              <Select value={role} onValueChange={v => { if (v) setRole(v); }}>
                <SelectTrigger id="new-role">
                  <SelectValue>{builtinRoleLabels[role] || role}</SelectValue>
                </SelectTrigger>
                <SelectContent>
                  {availableRoles
                    .filter((r) => r.name !== "super_admin")
                    .map((r) => (
                      <SelectItem key={r.name} value={r.name} label={builtinRoleLabels[r.name] ?? r.displayName}>
                        {builtinRoleLabels[r.name] ?? r.displayName}
                      </SelectItem>
                    ))}
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label htmlFor="new-password">{t("generatedPasswordLabel")}</Label>
              <Input
                id="new-password"
                type="password"
                value={password}
                onChange={e => setPassword(e.target.value)}
                required
              />
            </div>
            <DialogFooter>
              <Button type="button" variant="outline" onClick={() => handleOpenChange(false)} disabled={isLoading}>
                {tCommon("cancel")}
              </Button>
              <Button type="submit" disabled={isLoading}>
                {isLoading ? tCommon("loading") : tCommon("create")}
              </Button>
            </DialogFooter>
          </form>
      </DialogContent>
    </Dialog>
  );
}
