export const problems = [
  // ─── 스택/큐/덱 응용 (1–12) ─────────────────────────────────────────────────

  {
    title: "스택 수열",
    description: "1부터 N까지의 수를 오름차순으로 스택에 push하면서, 스택에서 pop하여 목표 수열을 만들 수 있는지 판단한다. 가능하면 push를 +, pop을 -로 출력하고, 불가능하면 \"NO\"를 출력한다.\n\n## 입력\n\n첫째 줄에 N이 주어진다. (1 ≤ N ≤ 100,000)\n둘째 줄부터 N개의 줄에 목표 수열의 원소가 순서대로 주어진다.\n\n## 출력\n\n만들 수 있으면 +와 -를 한 줄에 하나씩 출력한다. 만들 수 없으면 \"NO\"를 출력한다.\n\n## 예제 입력 1\n\n```\n8\n4\n3\n6\n8\n7\n5\n2\n1\n```\n\n## 예제 출력 1\n\n```\n+\n+\n+\n+\n-\n-\n+\n+\n-\n+\n-\n-\n-\n-\n-\n-\n```",
    difficulty: 4.5,
    timeLimitMs: 2000,
    memoryLimitMb: 256,
    comparisonMode: "exact",
    floatAbsoluteError: null,
    testCases: [
      { input: "8\n4\n3\n6\n8\n7\n5\n2\n1", expectedOutput: "+\n+\n+\n+\n-\n-\n+\n+\n-\n+\n-\n-\n-\n-\n-\n-", isVisible: true },
      { input: "5\n1\n2\n3\n4\n5", expectedOutput: "+\n-\n+\n-\n+\n-\n+\n-\n+\n-", isVisible: true },
      { input: "3\n3\n1\n2", expectedOutput: "NO", isVisible: false },
      { input: "5\n5\n4\n3\n2\n1", expectedOutput: "+\n+\n+\n+\n+\n-\n-\n-\n-\n-", isVisible: false },
      { input: "4\n2\n4\n1\n3", expectedOutput: "NO", isVisible: false },
    ],
    tags: ["자료구조", "스택"],
  },

  {
    title: "괄호의 값",
    description: "괄호 문자열에서 ()는 2, []는 3이다. (X)는 2×X, [X]는 3×X이고, 이웃한 값은 더한다. 올바른 괄호 문자열이 아니면 0을 출력한다.\n\n## 입력\n\n첫째 줄에 괄호 문자열이 주어진다. (길이 ≤ 30, (, ), [, ] 로만 구성)\n\n## 출력\n\n괄호 문자열의 값을 출력한다. 올바르지 않으면 0을 출력한다.\n\n## 예제 입력 1\n\n```\n(()[[]])([])\n```\n\n## 예제 출력 1\n\n```\n28\n```",
    difficulty: 5.5,
    timeLimitMs: 2000,
    memoryLimitMb: 256,
    comparisonMode: "exact",
    floatAbsoluteError: null,
    testCases: [
      { input: "(()[[]])([])", expectedOutput: "28", isVisible: true },
      { input: "()", expectedOutput: "2", isVisible: true },
      { input: "[][]", expectedOutput: "6", isVisible: false },
      { input: "([])", expectedOutput: "6", isVisible: false },
      { input: ")(", expectedOutput: "0", isVisible: false },
    ],
    tags: ["자료구조", "스택"],
  },

  {
    title: "오큰수 (NGE)",
    description: "N개의 수열에서 각 원소의 오른쪽에 있는 수 중, 자신보다 크면서 가장 가까운 수(오큰수)를 구한다. 오큰수가 없으면 -1을 출력한다.\n\n## 입력\n\n첫째 줄에 N이 주어진다. (1 ≤ N ≤ 1,000,000)\n둘째 줄에 N개의 정수가 공백으로 구분되어 주어진다. (1 ≤ Ai ≤ 1,000,000)\n\n## 출력\n\nN개의 오큰수를 공백으로 구분하여 한 줄에 출력한다.\n\n## 예제 입력 1\n\n```\n4\n3 5 2 7\n```\n\n## 예제 출력 1\n\n```\n5 7 7 -1\n```",
    difficulty: 5.0,
    timeLimitMs: 3000,
    memoryLimitMb: 256,
    comparisonMode: "exact",
    floatAbsoluteError: null,
    testCases: [
      { input: "4\n3 5 2 7", expectedOutput: "5 7 7 -1", isVisible: true },
      { input: "5\n9 5 4 8 2", expectedOutput: "-1 8 8 -1 -1", isVisible: true },
      { input: "1\n1", expectedOutput: "-1", isVisible: false },
      { input: "6\n1 2 3 4 5 6", expectedOutput: "2 3 4 5 6 -1", isVisible: false },
      { input: "5\n5 4 3 2 1", expectedOutput: "-1 -1 -1 -1 -1", isVisible: false },
    ],
    tags: ["자료구조", "스택"],
  },

  {
    title: "탑",
    description: "N개의 탑이 일렬로 세워져 있다. 각 탑 꼭대기에서 왼쪽 방향으로 레이저를 쏜다. 레이저를 수신하는 탑은 자신보다 높이가 크거나 같은 탑 중 가장 가까운 탑이다. 각 탑에서 쏜 레이저를 수신하는 탑의 번호를 출력한다. 수신하는 탑이 없으면 0을 출력한다.\n\n## 입력\n\n첫째 줄에 N이 주어진다. (1 ≤ N ≤ 500,000)\n둘째 줄에 N개의 탑의 높이가 공백으로 구분되어 주어진다. (1 ≤ Hi ≤ 100,000,000)\n\n## 출력\n\n각 탑에서 쏜 레이저를 수신하는 탑의 번호를 공백으로 구분하여 출력한다.\n\n## 예제 입력 1\n\n```\n5\n6 9 5 7 4\n```\n\n## 예제 출력 1\n\n```\n0 0 2 2 4\n```",
    difficulty: 5.0,
    timeLimitMs: 2000,
    memoryLimitMb: 256,
    comparisonMode: "exact",
    floatAbsoluteError: null,
    testCases: [
      { input: "5\n6 9 5 7 4", expectedOutput: "0 0 2 2 4", isVisible: true },
      { input: "3\n1 2 3", expectedOutput: "0 1 2", isVisible: true },
      { input: "1\n100", expectedOutput: "0", isVisible: false },
      { input: "5\n5 5 5 5 5", expectedOutput: "0 1 2 3 4", isVisible: false },
      { input: "6\n3 7 2 5 1 4", expectedOutput: "0 0 2 2 4 4", isVisible: false },
    ],
    tags: ["자료구조", "스택"],
  },

  {
    title: "히스토그램에서 가장 큰 직사각형",
    description: "N개의 막대로 이루어진 히스토그램에서 직사각형의 최대 넓이를 구한다. 각 막대의 너비는 1이다.\n\n## 입력\n\n첫째 줄에 N이 주어진다. (1 ≤ N ≤ 100,000)\n둘째 줄에 N개의 막대 높이가 공백으로 구분되어 주어진다. (0 ≤ Hi ≤ 1,000,000,000)\n\n## 출력\n\n히스토그램에서 넓이가 최대인 직사각형의 넓이를 출력한다.\n\n## 예제 입력 1\n\n```\n7\n2 1 4 5 1 3 3\n```\n\n## 예제 출력 1\n\n```\n8\n```",
    difficulty: 6.5,
    timeLimitMs: 3000,
    memoryLimitMb: 256,
    comparisonMode: "exact",
    floatAbsoluteError: null,
    testCases: [
      { input: "7\n2 1 4 5 1 3 3", expectedOutput: "8", isVisible: true },
      { input: "1\n10", expectedOutput: "10", isVisible: true },
      { input: "3\n3 3 3", expectedOutput: "9", isVisible: false },
      { input: "5\n1 2 3 4 5", expectedOutput: "9", isVisible: false },
      { input: "4\n0 0 0 0", expectedOutput: "0", isVisible: false },
    ],
    tags: ["자료구조", "스택"],
  },

  {
    title: "프린터 큐",
    description: "우선순위 프린터가 있다. N개의 문서가 큐에 있고, 각 문서는 중요도가 있다. 프린터는 큐의 맨 앞 문서보다 뒤에 중요도가 높은 문서가 있으면, 맨 앞 문서를 큐의 맨 뒤로 보낸다. 그렇지 않으면 인쇄한다. M번째 위치에 있는 문서가 몇 번째로 인쇄되는지 구한다. (0-indexed)\n\n## 입력\n\n첫째 줄에 테스트 케이스 수 T가 주어진다.\n각 테스트 케이스의 첫째 줄에 N과 M이 주어진다. (1 ≤ N ≤ 100, 0 ≤ M < N)\n둘째 줄에 N개의 문서 중요도가 공백으로 구분되어 주어진다. (1 ≤ 중요도 ≤ 9)\n\n## 출력\n\n각 테스트 케이스마다 M번째 문서가 몇 번째로 인쇄되는지 출력한다.\n\n## 예제 입력 1\n\n```\n3\n1 0\n5\n4 2\n1 2 3 4\n6 0\n1 1 9 1 1 1\n```\n\n## 예제 출력 1\n\n```\n1\n2\n5\n```",
    difficulty: 4.0,
    timeLimitMs: 2000,
    memoryLimitMb: 256,
    comparisonMode: "exact",
    floatAbsoluteError: null,
    testCases: [
      { input: "3\n1 0\n5\n4 2\n1 2 3 4\n6 0\n1 1 9 1 1 1", expectedOutput: "1\n2\n5", isVisible: true },
      { input: "1\n3 2\n1 1 1", expectedOutput: "3", isVisible: true },
      { input: "2\n5 0\n5 4 3 2 1\n3 1\n3 3 3", expectedOutput: "1\n2", isVisible: false },
      { input: "1\n1 0\n1", expectedOutput: "1", isVisible: false },
      { input: "1\n5 4\n1 2 3 4 5", expectedOutput: "1", isVisible: false },
    ],
    tags: ["자료구조", "큐"],
  },

  {
    title: "요세푸스 문제",
    description: "N명이 원형으로 앉아 있다. 순서대로 K번째 사람을 제거한다. 마지막 사람이 제거될 때까지 반복하며 제거 순서를 출력한다.\n\n## 입력\n\n첫째 줄에 N과 K가 주어진다. (1 ≤ K ≤ N ≤ 5,000)\n\n## 출력\n\n제거된 순서를 <N1, N2, ..., Nn> 형식으로 출력한다.\n\n## 예제 입력 1\n\n```\n7 3\n```\n\n## 예제 출력 1\n\n```\n<3, 6, 2, 7, 5, 1, 4>\n```",
    difficulty: 4.0,
    timeLimitMs: 2000,
    memoryLimitMb: 256,
    comparisonMode: "exact",
    floatAbsoluteError: null,
    testCases: [
      { input: "7 3", expectedOutput: "<3, 6, 2, 7, 5, 1, 4>", isVisible: true },
      { input: "1 1", expectedOutput: "<1>", isVisible: true },
      { input: "5 1", expectedOutput: "<1, 2, 3, 4, 5>", isVisible: false },
      { input: "5 5", expectedOutput: "<5, 4, 3, 1, 2>", isVisible: false },
      { input: "3 2", expectedOutput: "<2, 1, 3>", isVisible: false },
    ],
    tags: ["자료구조", "큐"],
  },

  {
    title: "큐 시뮬레이션",
    description: "정수를 저장하는 큐를 구현하고 다음 명령을 처리한다.\n- push X: 정수 X를 큐에 삽입\n- pop: 큐에서 가장 앞에 있는 정수를 제거하고 출력. 없으면 -1 출력\n- size: 큐에 들어 있는 정수 수 출력\n- empty: 큐가 비어 있으면 1, 아니면 0 출력\n- front: 큐의 가장 앞에 있는 정수를 출력. 없으면 -1 출력\n- back: 큐의 가장 뒤에 있는 정수를 출력. 없으면 -1 출력\n\n## 입력\n\n첫째 줄에 명령의 수 N이 주어진다. (1 ≤ N ≤ 10,000)\n둘째 줄부터 N개의 명령이 주어진다.\n\n## 출력\n\n출력이 있는 명령에 대해 결과를 한 줄에 하나씩 출력한다.\n\n## 예제 입력 1\n\n```\n9\npush 1\npush 2\nfront\nback\nsize\nempty\npop\npop\nempty\n```\n\n## 예제 출력 1\n\n```\n1\n2\n2\n0\n1\n2\n1\n```",
    difficulty: 4.0,
    timeLimitMs: 2000,
    memoryLimitMb: 256,
    comparisonMode: "exact",
    floatAbsoluteError: null,
    testCases: [
      { input: "9\npush 1\npush 2\nfront\nback\nsize\nempty\npop\npop\nempty", expectedOutput: "1\n2\n2\n0\n1\n2\n1", isVisible: true },
      { input: "3\nempty\npush 5\nempty", expectedOutput: "1\n0", isVisible: true },
      { input: "4\npop\nfront\nback\nsize", expectedOutput: "-1\n-1\n-1\n0", isVisible: false },
      { input: "5\npush 10\npush 20\npop\nfront\nsize", expectedOutput: "10\n20\n1", isVisible: false },
      { input: "6\npush 3\npush 4\npush 5\npop\npop\npop", expectedOutput: "3\n4\n5", isVisible: false },
    ],
    tags: ["자료구조", "큐"],
  },

  {
    title: "덱 시뮬레이션",
    description: "정수를 저장하는 덱(Deque)을 구현하고 다음 명령을 처리한다.\n- push_front X: 덱 앞에 X 삽입\n- push_back X: 덱 뒤에 X 삽입\n- pop_front: 덱 앞의 값을 제거하고 출력. 없으면 -1\n- pop_back: 덱 뒤의 값을 제거하고 출력. 없으면 -1\n- size: 덱의 크기 출력\n- empty: 비어 있으면 1, 아니면 0 출력\n- front: 덱 앞의 값 출력. 없으면 -1\n- back: 덱 뒤의 값 출력. 없으면 -1\n\n## 입력\n\n첫째 줄에 명령의 수 N이 주어진다. (1 ≤ N ≤ 10,000)\n둘째 줄부터 N개의 명령이 주어진다.\n\n## 출력\n\n출력이 있는 명령에 대해 결과를 한 줄에 하나씩 출력한다.\n\n## 예제 입력 1\n\n```\n10\npush_back 1\npush_front 2\nfront\nback\nsize\nempty\npop_front\npop_back\npop_front\nsize\n```\n\n## 예제 출력 1\n\n```\n2\n1\n2\n0\n2\n1\n-1\n0\n```",
    difficulty: 4.0,
    timeLimitMs: 2000,
    memoryLimitMb: 256,
    comparisonMode: "exact",
    floatAbsoluteError: null,
    testCases: [
      { input: "10\npush_back 1\npush_front 2\nfront\nback\nsize\nempty\npop_front\npop_back\npop_front\nsize", expectedOutput: "2\n1\n2\n0\n2\n1\n-1\n0", isVisible: true },
      { input: "3\nempty\npush_front 7\nfront", expectedOutput: "1\n7", isVisible: true },
      { input: "4\npop_front\npop_back\nfront\nback", expectedOutput: "-1\n-1\n-1\n-1", isVisible: false },
      { input: "5\npush_back 1\npush_back 2\npush_back 3\npop_front\npop_back", expectedOutput: "1\n3", isVisible: false },
      { input: "6\npush_front 5\npush_front 3\npush_front 1\npop_front\npop_front\npop_front", expectedOutput: "1\n3\n5", isVisible: false },
    ],
    tags: ["자료구조", "덱"],
  },

  {
    title: "슬라이딩 윈도우 최솟값",
    description: "N개의 정수로 이루어진 수열이 있다. 크기가 K인 슬라이딩 윈도우가 왼쪽에서 오른쪽으로 이동할 때, 각 윈도우 내의 최솟값을 구한다.\n\n## 입력\n\n첫째 줄에 N과 K가 주어진다. (1 ≤ K ≤ N ≤ 5,000,000)\n둘째 줄에 N개의 정수가 공백으로 구분되어 주어진다. (0 ≤ Ai ≤ 1,000,000,000)\n\n## 출력\n\n각 윈도우의 최솟값을 공백으로 구분하여 한 줄에 출력한다.\n\n## 예제 입력 1\n\n```\n8 3\n1 3 -1 -3 5 3 6 7\n```\n\n## 예제 출력 1\n\n```\n-1 -3 -3 -3 3 3\n```",
    difficulty: 6.0,
    timeLimitMs: 5000,
    memoryLimitMb: 512,
    comparisonMode: "exact",
    floatAbsoluteError: null,
    testCases: [
      { input: "8 3\n1 3 -1 -3 5 3 6 7", expectedOutput: "-1 -3 -3 -3 3 3", isVisible: true },
      { input: "5 1\n5 4 3 2 1", expectedOutput: "5 4 3 2 1", isVisible: true },
      { input: "5 5\n1 2 3 4 5", expectedOutput: "1", isVisible: false },
      { input: "6 2\n3 1 4 1 5 9", expectedOutput: "1 1 1 1 5", isVisible: false },
      { input: "4 3\n2 2 2 2", expectedOutput: "2 2", isVisible: false },
    ],
    tags: ["자료구조", "덱"],
  },

  {
    title: "슬라이딩 윈도우 최댓값",
    description: "N개의 정수로 이루어진 수열이 있다. 크기가 K인 슬라이딩 윈도우가 왼쪽에서 오른쪽으로 이동할 때, 각 윈도우 내의 최댓값을 구한다.\n\n## 입력\n\n첫째 줄에 N과 K가 주어진다. (1 ≤ K ≤ N ≤ 5,000,000)\n둘째 줄에 N개의 정수가 공백으로 구분되어 주어진다. (0 ≤ Ai ≤ 1,000,000,000)\n\n## 출력\n\n각 윈도우의 최댓값을 공백으로 구분하여 한 줄에 출력한다.\n\n## 예제 입력 1\n\n```\n8 3\n1 3 -1 -3 5 3 6 7\n```\n\n## 예제 출력 1\n\n```\n3 3 5 5 6 7\n```",
    difficulty: 6.0,
    timeLimitMs: 5000,
    memoryLimitMb: 512,
    comparisonMode: "exact",
    floatAbsoluteError: null,
    testCases: [
      { input: "8 3\n1 3 -1 -3 5 3 6 7", expectedOutput: "3 3 5 5 6 7", isVisible: true },
      { input: "5 1\n1 2 3 4 5", expectedOutput: "1 2 3 4 5", isVisible: true },
      { input: "5 5\n5 4 3 2 1", expectedOutput: "5", isVisible: false },
      { input: "6 2\n3 1 4 1 5 9", expectedOutput: "3 4 4 5 9", isVisible: false },
      { input: "4 2\n2 2 2 2", expectedOutput: "2 2 2", isVisible: false },
    ],
    tags: ["자료구조", "덱"],
  },

  {
    title: "후위 표기식 변환",
    description: "중위 표기식을 후위 표기식으로 변환한다. 피연산자는 알파벳 대문자(A-Z)이고, 연산자는 +, -, *, /, (, )이다. 연산자 우선순위는 *, /가 +, -보다 높으며, 괄호 안의 식을 먼저 계산한다.\n\n## 입력\n\n첫째 줄에 중위 표기식이 주어진다. (길이 ≤ 100, 피연산자는 A-Z, 연산자는 +,-,*,/,(,))\n\n## 출력\n\n후위 표기식을 출력한다.\n\n## 예제 입력 1\n\n```\nA+B*C-D/E\n```\n\n## 예제 출력 1\n\n```\nABC*+DE/-\n```",
    difficulty: 5.5,
    timeLimitMs: 2000,
    memoryLimitMb: 256,
    comparisonMode: "exact",
    floatAbsoluteError: null,
    testCases: [
      { input: "A+B*C-D/E", expectedOutput: "ABC*+DE/-", isVisible: true },
      { input: "A+B", expectedOutput: "AB+", isVisible: true },
      { input: "(A+B)*C", expectedOutput: "AB+C*", isVisible: false },
      { input: "A*(B+C)-D", expectedOutput: "ABC+*D-", isVisible: false },
      { input: "(A+B)*(C-D)", expectedOutput: "AB+CD-*", isVisible: false },
    ],
    tags: ["자료구조", "스택"],
  },

  // ─── 우선순위 큐/힙 (13–20) ──────────────────────────────────────────────────

  {
    title: "최대 힙",
    description: "N개의 연산을 처리하는 최대 힙을 구현한다.\n- 양수 x: 힙에 x 삽입\n- 0: 힙에서 가장 큰 값을 출력하고 제거. 힙이 비어 있으면 0 출력\n\n## 입력\n\n첫째 줄에 연산의 수 N이 주어진다. (1 ≤ N ≤ 100,000)\n둘째 줄부터 N개의 연산이 주어진다.\n\n## 출력\n\n0 연산에 대한 결과를 한 줄에 하나씩 출력한다.\n\n## 예제 입력 1\n\n```\n9\n5\n2\n0\n3\n0\n0\n0\n1\n0\n```\n\n## 예제 출력 1\n\n```\n5\n3\n2\n0\n1\n```",
    difficulty: 4.5,
    timeLimitMs: 2000,
    memoryLimitMb: 256,
    comparisonMode: "exact",
    floatAbsoluteError: null,
    testCases: [
      { input: "9\n5\n2\n0\n3\n0\n0\n0\n1\n0", expectedOutput: "5\n3\n2\n0\n1", isVisible: true },
      { input: "3\n0\n1\n0", expectedOutput: "0\n1", isVisible: true },
      { input: "5\n10\n5\n1\n0\n0", expectedOutput: "10\n5", isVisible: false },
      { input: "4\n3\n3\n0\n0", expectedOutput: "3\n3", isVisible: false },
      { input: "1\n0", expectedOutput: "0", isVisible: false },
    ],
    tags: ["자료구조", "우선순위 큐"],
  },

  {
    title: "최소 힙",
    description: "N개의 연산을 처리하는 최소 힙을 구현한다.\n- 양수 x: 힙에 x 삽입\n- 0: 힙에서 가장 작은 값을 출력하고 제거. 힙이 비어 있으면 0 출력\n\n## 입력\n\n첫째 줄에 연산의 수 N이 주어진다. (1 ≤ N ≤ 100,000)\n둘째 줄부터 N개의 연산이 주어진다.\n\n## 출력\n\n0 연산에 대한 결과를 한 줄에 하나씩 출력한다.\n\n## 예제 입력 1\n\n```\n9\n5\n2\n0\n3\n0\n0\n0\n1\n0\n```\n\n## 예제 출력 1\n\n```\n2\n3\n5\n0\n1\n```",
    difficulty: 4.5,
    timeLimitMs: 2000,
    memoryLimitMb: 256,
    comparisonMode: "exact",
    floatAbsoluteError: null,
    testCases: [
      { input: "9\n5\n2\n0\n3\n0\n0\n0\n1\n0", expectedOutput: "2\n3\n5\n0\n1", isVisible: true },
      { input: "3\n0\n1\n0", expectedOutput: "0\n1", isVisible: true },
      { input: "5\n10\n5\n1\n0\n0", expectedOutput: "1\n5", isVisible: false },
      { input: "4\n3\n3\n0\n0", expectedOutput: "3\n3", isVisible: false },
      { input: "1\n0", expectedOutput: "0", isVisible: false },
    ],
    tags: ["자료구조", "우선순위 큐"],
  },

  {
    title: "절댓값 힙",
    description: "N개의 연산을 처리하는 절댓값 힙을 구현한다.\n- 0이 아닌 정수 x: 힙에 x 삽입\n- 0: 힙에서 절댓값이 가장 작은 값을 출력하고 제거. 절댓값이 같으면 실제 값이 더 작은 것을 출력. 힙이 비어 있으면 0 출력\n\n## 입력\n\n첫째 줄에 연산의 수 N이 주어진다. (1 ≤ N ≤ 100,000)\n둘째 줄부터 N개의 연산이 주어진다. (정수 범위: -2^31 + 1 이상 2^31 - 1 이하)\n\n## 출력\n\n0 연산에 대한 결과를 한 줄에 하나씩 출력한다.\n\n## 예제 입력 1\n\n```\n7\n1\n-1\n0\n0\n0\n2\n0\n```\n\n## 예제 출력 1\n\n```\n-1\n1\n0\n2\n```",
    difficulty: 5.0,
    timeLimitMs: 2000,
    memoryLimitMb: 256,
    comparisonMode: "exact",
    floatAbsoluteError: null,
    testCases: [
      { input: "7\n1\n-1\n0\n0\n0\n2\n0", expectedOutput: "-1\n1\n0\n2", isVisible: true },
      { input: "3\n0\n5\n0", expectedOutput: "0\n5", isVisible: true },
      { input: "5\n-3\n3\n0\n0\n0", expectedOutput: "-3\n3\n0", isVisible: false },
      { input: "4\n10\n-10\n5\n0", expectedOutput: "5", isVisible: false },
      { input: "1\n0", expectedOutput: "0", isVisible: false },
    ],
    tags: ["자료구조", "우선순위 큐"],
  },

  {
    title: "이중 우선순위 큐",
    description: "이중 우선순위 큐(Double-Ended Priority Queue)를 구현한다. 다음 명령을 처리한다.\n- I N: 정수 N을 삽입\n- D 1: 최댓값 삭제\n- D -1: 최솟값 삭제\n모든 연산을 처리한 후 큐에 남은 원소의 최댓값과 최솟값을 출력한다. 큐가 비어 있으면 \"EMPTY\"를 출력한다.\n\n## 입력\n\n첫째 줄에 테스트 케이스 수 T가 주어진다.\n각 테스트 케이스의 첫째 줄에 연산 수 k가 주어진다. (1 ≤ k ≤ 1,000,000)\n다음 k개의 줄에 연산이 주어진다.\n\n## 출력\n\n각 테스트 케이스마다 최댓값과 최솟값을 공백으로 구분하여 출력하거나 \"EMPTY\"를 출력한다.\n\n## 예제 입력 1\n\n```\n2\n7\nI 16\nI -5643\nD -1\nD 1\nD 1\nI 123\nD -1\n2\nI -45\nI 653\n```\n\n## 예제 출력 1\n\n```\nEMPTY\n653 -45\n```",
    difficulty: 5.5,
    timeLimitMs: 3000,
    memoryLimitMb: 256,
    comparisonMode: "exact",
    floatAbsoluteError: null,
    testCases: [
      { input: "2\n7\nI 16\nI -5643\nD -1\nD 1\nD 1\nI 123\nD -1\n2\nI -45\nI 653", expectedOutput: "EMPTY\n653 -45", isVisible: true },
      { input: "1\n3\nI 1\nI 2\nI 3", expectedOutput: "3 1", isVisible: true },
      { input: "1\n1\nD 1", expectedOutput: "EMPTY", isVisible: false },
      { input: "1\n4\nI 5\nI 5\nD 1\nD 1", expectedOutput: "EMPTY", isVisible: false },
      { input: "1\n5\nI 10\nI 20\nI 30\nD 1\nD -1", expectedOutput: "20 20", isVisible: false },
    ],
    tags: ["자료구조", "우선순위 큐"],
  },

  {
    title: "중앙값 구하기",
    description: "수를 하나씩 입력받을 때, 홀수 개의 수가 입력될 때마다 그 중앙값을 출력한다. 중앙값은 정렬했을 때 가운데에 있는 값이다.\n\n## 입력\n\n첫째 줄에 입력할 수의 개수 N이 주어진다. (1 ≤ N ≤ 100,000)\n둘째 줄부터 N개의 정수가 한 줄에 하나씩 주어진다. (-10,000 ≤ Ai ≤ 10,000)\n\n## 출력\n\n홀수 번째 수가 입력될 때마다 중앙값을 한 줄에 출력한다. 총 ⌈N/2⌉개의 중앙값을 출력한다.\n\n## 예제 입력 1\n\n```\n9\n1\n5\n2\n10\n-99\n7\n5\n-1\n100\n```\n\n## 예제 출력 1\n\n```\n1\n2\n2\n5\n5\n```",
    difficulty: 6.0,
    timeLimitMs: 2000,
    memoryLimitMb: 256,
    comparisonMode: "exact",
    floatAbsoluteError: null,
    testCases: [
      { input: "9\n1\n5\n2\n10\n-99\n7\n5\n-1\n100", expectedOutput: "1\n2\n2\n5\n5", isVisible: true },
      { input: "1\n7", expectedOutput: "7", isVisible: true },
      { input: "3\n3\n1\n2", expectedOutput: "3\n2", isVisible: false },
      { input: "5\n5\n3\n1\n2\n4", expectedOutput: "5\n3\n3", isVisible: false },
      { input: "4\n-1\n-2\n-3\n-4", expectedOutput: "-1\n-2", isVisible: false },
    ],
    tags: ["자료구조", "우선순위 큐"],
  },

  {
    title: "K번째 수 (스트림)",
    description: "수를 하나씩 입력받을 때, 매번 K번째로 작은 수를 출력한다. K번째 수가 없으면 -1을 출력한다.\n\n## 입력\n\n첫째 줄에 N과 K가 주어진다. (1 ≤ K ≤ N ≤ 100,000)\n둘째 줄부터 N개의 정수가 한 줄에 하나씩 주어진다. (1 ≤ Ai ≤ 10^9)\n\n## 출력\n\n각 수가 입력될 때마다 K번째로 작은 수를 한 줄에 출력한다.\n\n## 예제 입력 1\n\n```\n5 3\n1\n5\n2\n6\n3\n```\n\n## 예제 출력 1\n\n```\n-1\n-1\n2\n2\n3\n```",
    difficulty: 5.5,
    timeLimitMs: 2000,
    memoryLimitMb: 256,
    comparisonMode: "exact",
    floatAbsoluteError: null,
    testCases: [
      { input: "5 3\n1\n5\n2\n6\n3", expectedOutput: "-1\n-1\n2\n2\n3", isVisible: true },
      { input: "3 1\n10\n5\n1", expectedOutput: "10\n5\n1", isVisible: true },
      { input: "4 2\n3\n1\n4\n1", expectedOutput: "-1\n3\n3\n3", isVisible: false },
      { input: "5 5\n5\n4\n3\n2\n1", expectedOutput: "-1\n-1\n-1\n-1\n5", isVisible: false },
      { input: "3 3\n1\n2\n3", expectedOutput: "-1\n-1\n3", isVisible: false },
    ],
    tags: ["자료구조", "우선순위 큐"],
  },

  {
    title: "가장 먼 노드",
    description: "N개의 노드로 이루어진 가중치 1인 무향 그래프가 있다. 1번 노드에서 가장 멀리 떨어진 노드의 개수를 구한다. (최단 경로의 길이가 가장 긴 노드의 개수)\n\n## 입력\n\n첫째 줄에 N과 간선의 수 E가 주어진다. (2 ≤ N ≤ 20,000, 1 ≤ E ≤ 300,000)\n둘째 줄부터 E개의 줄에 간선의 양 끝점 u, v가 주어진다.\n\n## 출력\n\n1번 노드에서 가장 먼 노드의 개수를 출력한다.\n\n## 예제 입력 1\n\n```\n6 6\n3 6\n4 3\n3 2\n1 3\n1 2\n2 4\n```\n\n## 예제 출력 1\n\n```\n3\n```",
    difficulty: 5.0,
    timeLimitMs: 2000,
    memoryLimitMb: 256,
    comparisonMode: "exact",
    floatAbsoluteError: null,
    testCases: [
      { input: "6 6\n3 6\n4 3\n3 2\n1 3\n1 2\n2 4", expectedOutput: "3", isVisible: true },
      { input: "2 1\n1 2", expectedOutput: "1", isVisible: true },
      { input: "4 4\n1 2\n1 3\n2 4\n3 4", expectedOutput: "2", isVisible: false },
      { input: "5 4\n1 2\n2 3\n3 4\n4 5", expectedOutput: "1", isVisible: false },
      { input: "4 3\n1 2\n1 3\n1 4", expectedOutput: "3", isVisible: false },
    ],
    tags: ["자료구조", "그래프", "BFS"],
  },

  {
    title: "디스크 컨트롤러",
    description: "각 작업은 요청 시간과 소요 시간이 있다. 한 번에 하나의 작업만 처리할 수 있을 때, 모든 작업의 반환 시간(요청~완료)의 평균을 최소화하는 순서로 처리한다. 평균 반환 시간의 소수점 이하는 버린다. (SJF 알고리즘 변형)\n\n## 입력\n\n첫째 줄에 작업 수 N이 주어진다. (1 ≤ N ≤ 500)\n둘째 줄부터 N개의 줄에 요청 시간과 소요 시간이 공백으로 구분되어 주어진다. (0 ≤ 요청 시간 ≤ 1,000, 1 ≤ 소요 시간 ≤ 1,000)\n\n## 출력\n\n모든 작업의 반환 시간 평균(소수점 버림)을 출력한다.\n\n## 예제 입력 1\n\n```\n3\n0 3\n1 9\n2 6\n```\n\n## 예제 출력 1\n\n```\n9\n```",
    difficulty: 6.0,
    timeLimitMs: 2000,
    memoryLimitMb: 256,
    comparisonMode: "exact",
    floatAbsoluteError: null,
    testCases: [
      { input: "3\n0 3\n1 9\n2 6", expectedOutput: "9", isVisible: true },
      { input: "1\n0 5", expectedOutput: "5", isVisible: true },
      { input: "2\n0 10\n0 1", expectedOutput: "6", isVisible: false },
      { input: "3\n0 1\n0 1\n0 1", expectedOutput: "2", isVisible: false },
      { input: "2\n0 5\n10 1", expectedOutput: "3", isVisible: false },
    ],
    tags: ["자료구조", "우선순위 큐"],
  },

  // ─── Union-Find (21–27) ───────────────────────────────────────────────────────

  {
    title: "집합의 표현",
    description: "초기에 {0}, {1}, ..., {N}의 N+1개의 집합이 있다. 다음 두 연산을 처리한다.\n- 0 a b: a와 b가 속한 집합을 합친다 (Union)\n- 1 a b: a와 b가 같은 집합에 있으면 \"YES\", 아니면 \"NO\" 출력 (Find)\n\n## 입력\n\n첫째 줄에 N과 M이 주어진다. (1 ≤ N ≤ 1,000,000, 1 ≤ M ≤ 100,000)\n둘째 줄부터 M개의 연산이 주어진다.\n\n## 출력\n\nFind 연산(1)에 대해 결과를 한 줄에 하나씩 출력한다.\n\n## 예제 입력 1\n\n```\n7 8\n0 1 3\n1 1 7\n0 7 6\n1 7 1\n0 3 7\n0 0 4\n0 5 2\n1 0 6\n```\n\n## 예제 출력 1\n\n```\nNO\nNO\nNO\n```",
    difficulty: 5.0,
    timeLimitMs: 3000,
    memoryLimitMb: 256,
    comparisonMode: "exact",
    floatAbsoluteError: null,
    testCases: [
      { input: "7 8\n0 1 3\n1 1 7\n0 7 6\n1 7 1\n0 3 7\n0 0 4\n0 5 2\n1 0 6", expectedOutput: "NO\nNO\nNO", isVisible: true },
      { input: "3 3\n0 1 2\n0 2 3\n1 1 3", expectedOutput: "YES", isVisible: true },
      { input: "2 2\n1 1 2\n0 1 2", expectedOutput: "NO", isVisible: false },
      { input: "5 4\n0 1 2\n0 3 4\n1 1 3\n0 2 3", expectedOutput: "NO", isVisible: false },
      { input: "3 3\n0 1 2\n1 1 2\n1 1 3", expectedOutput: "YES\nNO", isVisible: false },
    ],
    tags: ["자료구조", "유니온파인드"],
  },

  {
    title: "여행 가자",
    description: "N개의 도시와 M개의 도로가 있다. 여행 계획에 방문할 도시 V개가 주어질 때, 이 도시들이 모두 서로 연결되어 있는지 확인한다.\n\n## 입력\n\n첫째 줄에 N, M이 주어진다. (1 ≤ N ≤ 200, 1 ≤ M ≤ N*(N-1)/2)\n둘째 줄부터 M개의 줄에 도로 양 끝 도시 번호가 주어진다.\nN+M+1번째 줄에 여행 계획 도시 수 V와 V개의 도시 번호가 주어진다.\n\n## 출력\n\n모두 연결되어 있으면 \"YES\", 아니면 \"NO\"를 출력한다.\n\n## 예제 입력 1\n\n```\n5 4\n1 2\n2 3\n3 4\n4 5\n4 2 3 4 5\n```\n\n## 예제 출력 1\n\n```\nYES\n```",
    difficulty: 5.0,
    timeLimitMs: 2000,
    memoryLimitMb: 256,
    comparisonMode: "exact",
    floatAbsoluteError: null,
    testCases: [
      { input: "5 4\n1 2\n2 3\n3 4\n4 5\n4 2 3 4 5", expectedOutput: "YES", isVisible: true },
      { input: "4 2\n1 2\n3 4\n2 1 3", expectedOutput: "NO", isVisible: true },
      { input: "3 3\n1 2\n2 3\n1 3\n3 1 2 3", expectedOutput: "YES", isVisible: false },
      { input: "5 2\n1 2\n3 4\n2 1 2", expectedOutput: "YES", isVisible: false },
      { input: "5 1\n1 2\n3 2 3 4", expectedOutput: "NO", isVisible: false },
    ],
    tags: ["자료구조", "유니온파인드"],
  },

  {
    title: "친구 네트워크",
    description: "친구 관계가 주어질 때, 각 관계를 추가할 때마다 두 사람이 속한 네트워크(연결된 사람들의 집합)의 크기를 출력한다.\n\n## 입력\n\n첫째 줄에 테스트 케이스 수 T가 주어진다.\n각 테스트 케이스의 첫째 줄에 친구 관계 수 F가 주어진다. (1 ≤ F ≤ 100,000)\n다음 F개의 줄에 두 사람의 이름이 주어진다. (이름은 알파벳 소문자, 길이 ≤ 20)\n\n## 출력\n\n각 관계 추가 후 해당 네트워크의 크기를 출력한다.\n\n## 예제 입력 1\n\n```\n2\n3\nfriends network yes\nyes no\nno yes\n3\na b\nb c\nc d\n```\n\n## 예제 출력 1\n\n```\n2\n3\n4\n2\n3\n4\n```",
    difficulty: 5.5,
    timeLimitMs: 2000,
    memoryLimitMb: 256,
    comparisonMode: "exact",
    floatAbsoluteError: null,
    testCases: [
      { input: "2\n3\nfriends network yes\nyes no\nno yes\n3\na b\nb c\nc d", expectedOutput: "2\n3\n4\n2\n3\n4", isVisible: true },
      { input: "1\n1\nalice bob", expectedOutput: "2", isVisible: true },
      { input: "1\n3\na b\nb c\na c", expectedOutput: "2\n3\n3", isVisible: false },
      { input: "1\n2\nx y\ny z", expectedOutput: "2\n3", isVisible: false },
      { input: "1\n4\na b\nb c\nc d\nd e", expectedOutput: "2\n3\n4\n5", isVisible: false },
    ],
    tags: ["자료구조", "유니온파인드"],
  },

  {
    title: "거짓말",
    description: "N명의 사람과 M개의 파티가 있다. 지민이는 각 파티에서 거짓말을 하거나 진실을 말한다. 진실을 아는 사람과 같은 파티에 있으면 거짓말을 할 수 없다. 진실을 아는 사람들의 집합과 연결된 모든 파티에서는 거짓말 불가. 거짓말을 할 수 있는 파티의 최대 수를 구한다.\n\n## 입력\n\n첫째 줄에 N, M이 주어진다. (1 ≤ N ≤ 50, 1 ≤ M ≤ 50)\n둘째 줄에 진실을 아는 사람 수 K와 K명의 번호가 주어진다.\n다음 M개의 줄에 파티 참가자 수와 참가자 번호가 주어진다.\n\n## 출력\n\n거짓말을 할 수 있는 파티의 최대 수를 출력한다.\n\n## 예제 입력 1\n\n```\n4 3\n2 1 2\n2 1 3\n1 3\n3 2 3 4\n```\n\n## 예제 출력 1\n\n```\n1\n```",
    difficulty: 5.5,
    timeLimitMs: 2000,
    memoryLimitMb: 256,
    comparisonMode: "exact",
    floatAbsoluteError: null,
    testCases: [
      { input: "4 3\n2 1 2\n2 1 3\n1 3\n3 2 3 4", expectedOutput: "1", isVisible: true },
      { input: "3 2\n0\n2 1 2\n2 2 3", expectedOutput: "2", isVisible: true },
      { input: "2 1\n1 1\n2 1 2", expectedOutput: "0", isVisible: false },
      { input: "5 3\n1 1\n2 2 3\n2 3 4\n2 4 5", expectedOutput: "1", isVisible: false },
      { input: "4 4\n0\n1 1\n1 2\n1 3\n1 4", expectedOutput: "4", isVisible: false },
    ],
    tags: ["자료구조", "유니온파인드"],
  },

  {
    title: "네트워크 연결 (Union-Find)",
    description: "N개의 컴퓨터와 Q개의 쿼리가 주어진다. 쿼리는 두 가지이다.\n- 1 a b: a와 b를 연결한다\n- 2 a b: a와 b가 연결되어 있으면 \"YES\", 아니면 \"NO\" 출력\n\n## 입력\n\n첫째 줄에 N과 Q가 주어진다. (1 ≤ N ≤ 100,000, 1 ≤ Q ≤ 100,000)\n둘째 줄부터 Q개의 쿼리가 주어진다.\n\n## 출력\n\n2번 쿼리에 대한 결과를 한 줄에 하나씩 출력한다.\n\n## 예제 입력 1\n\n```\n5 5\n1 1 2\n2 1 3\n1 2 3\n2 1 3\n2 4 5\n```\n\n## 예제 출력 1\n\n```\nNO\nYES\nNO\n```",
    difficulty: 5.0,
    timeLimitMs: 2000,
    memoryLimitMb: 256,
    comparisonMode: "exact",
    floatAbsoluteError: null,
    testCases: [
      { input: "5 5\n1 1 2\n2 1 3\n1 2 3\n2 1 3\n2 4 5", expectedOutput: "NO\nYES\nNO", isVisible: true },
      { input: "3 3\n1 1 2\n1 2 3\n2 1 3", expectedOutput: "YES", isVisible: true },
      { input: "4 4\n2 1 2\n1 1 2\n2 1 2\n2 3 4", expectedOutput: "NO\nYES\nNO", isVisible: false },
      { input: "2 2\n1 1 2\n2 1 2", expectedOutput: "YES", isVisible: false },
      { input: "5 3\n2 1 5\n1 1 5\n2 1 5", expectedOutput: "NO\nYES", isVisible: false },
    ],
    tags: ["자료구조", "유니온파인드"],
  },

  {
    title: "최소 스패닝 트리 (크루스칼)",
    description: "N개의 정점과 M개의 간선이 있는 가중치 그래프에서 최소 스패닝 트리(MST)의 가중치 합을 구한다. Union-Find 기반 크루스칼 알고리즘을 사용한다.\n\n## 입력\n\n첫째 줄에 N과 M이 주어진다. (1 ≤ N ≤ 100,000, 1 ≤ M ≤ 1,000,000)\n둘째 줄부터 M개의 줄에 간선의 양 끝 정점 u, v와 가중치 w가 주어진다. (1 ≤ w ≤ 1,000,000)\n\n## 출력\n\nMST의 총 가중치를 출력한다.\n\n## 예제 입력 1\n\n```\n4 5\n1 2 1\n1 3 4\n2 3 2\n2 4 5\n3 4 3\n```\n\n## 예제 출력 1\n\n```\n6\n```",
    difficulty: 5.5,
    timeLimitMs: 3000,
    memoryLimitMb: 256,
    comparisonMode: "exact",
    floatAbsoluteError: null,
    testCases: [
      { input: "4 5\n1 2 1\n1 3 4\n2 3 2\n2 4 5\n3 4 3", expectedOutput: "6", isVisible: true },
      { input: "2 1\n1 2 10", expectedOutput: "10", isVisible: true },
      { input: "3 3\n1 2 1\n2 3 1\n1 3 100", expectedOutput: "2", isVisible: false },
      { input: "5 6\n1 2 1\n2 3 2\n3 4 3\n4 5 4\n1 5 10\n2 4 5", expectedOutput: "10", isVisible: false },
      { input: "3 3\n1 2 5\n2 3 3\n1 3 4", expectedOutput: "7", isVisible: false },
    ],
    tags: ["자료구조", "유니온파인드", "그래프"],
  },

  {
    title: "사이클 게임",
    description: "무향 그래프에 간선을 하나씩 추가할 때, 처음으로 사이클이 생기는 시점(몇 번째 간선 추가 후)을 출력한다. 사이클이 생기지 않으면 0을 출력한다.\n\n## 입력\n\n첫째 줄에 정점 수 N과 간선 수 M이 주어진다. (1 ≤ N ≤ 500,000, 1 ≤ M ≤ 1,000,000)\n둘째 줄부터 M개의 줄에 간선의 양 끝 정점 u, v가 주어진다.\n\n## 출력\n\n처음으로 사이클이 생기는 시점의 번호를 출력한다. 사이클이 생기지 않으면 0을 출력한다.\n\n## 예제 입력 1\n\n```\n4 5\n1 2\n2 3\n3 4\n4 2\n1 3\n```\n\n## 예제 출력 1\n\n```\n4\n```",
    difficulty: 5.5,
    timeLimitMs: 3000,
    memoryLimitMb: 256,
    comparisonMode: "exact",
    floatAbsoluteError: null,
    testCases: [
      { input: "4 5\n1 2\n2 3\n3 4\n4 2\n1 3", expectedOutput: "4", isVisible: true },
      { input: "3 2\n1 2\n2 3", expectedOutput: "0", isVisible: true },
      { input: "3 3\n1 2\n2 3\n1 3", expectedOutput: "3", isVisible: false },
      { input: "5 5\n1 2\n3 4\n2 3\n4 5\n5 1", expectedOutput: "5", isVisible: false },
      { input: "2 2\n1 2\n1 2", expectedOutput: "2", isVisible: false },
    ],
    tags: ["자료구조", "유니온파인드"],
  },

  // ─── 세그먼트 트리 / 펜윅 트리 (28–35) ──────────────────────────────────────

  {
    title: "구간 합 구하기 (세그먼트 트리)",
    description: "N개의 수로 이루어진 수열이 있다. 두 종류의 연산을 처리한다.\n- 1 i v: i번째 수를 v로 변경\n- 2 l r: l번째부터 r번째까지의 합을 출력\n\n## 입력\n\n첫째 줄에 N, M, K가 주어진다. (1 ≤ N ≤ 1,000,000, 1 ≤ M+K ≤ 20,000)\nM은 변경 횟수, K는 구간 합 쿼리 횟수이다.\n둘째 줄에 N개의 정수가 공백으로 구분되어 주어진다. (각 수의 크기 ≤ 1,000,000)\n다음 M+K개의 줄에 연산이 주어진다.\n\n## 출력\n\n2번 연산에 대한 결과를 한 줄에 하나씩 출력한다.\n\n## 예제 입력 1\n\n```\n5 2 2\n1 2 3 4 5\n1 3 10\n2 1 5\n1 1 0\n2 2 4\n```\n\n## 예제 출력 1\n\n```\n21\n14\n```",
    difficulty: 6.0,
    timeLimitMs: 3000,
    memoryLimitMb: 256,
    comparisonMode: "exact",
    floatAbsoluteError: null,
    testCases: [
      { input: "5 2 2\n1 2 3 4 5\n1 3 10\n2 1 5\n1 1 0\n2 2 4", expectedOutput: "21\n14", isVisible: true },
      { input: "3 0 1\n1 2 3\n2 1 3", expectedOutput: "6", isVisible: true },
      { input: "4 1 2\n4 3 2 1\n1 2 5\n2 1 4\n2 2 3", expectedOutput: "13\n7", isVisible: false },
      { input: "1 1 1\n5\n1 1 10\n2 1 1", expectedOutput: "10", isVisible: false },
      { input: "5 0 3\n1 1 1 1 1\n2 1 5\n2 2 4\n2 3 3", expectedOutput: "5\n3\n1", isVisible: false },
    ],
    tags: ["자료구조", "세그먼트 트리"],
  },

  {
    title: "구간 최솟값 쿼리 (RMQ)",
    description: "N개의 수로 이루어진 수열이 있다. M개의 쿼리가 주어지며, 각 쿼리 [L, R]에 대해 L번째부터 R번째 수 중 최솟값을 출력한다.\n\n## 입력\n\n첫째 줄에 N과 M이 주어진다. (1 ≤ N ≤ 100,000, 1 ≤ M ≤ 100,000)\n둘째 줄에 N개의 정수가 공백으로 구분되어 주어진다. (1 ≤ Ai ≤ 10^9)\n다음 M개의 줄에 L과 R이 주어진다. (1 ≤ L ≤ R ≤ N)\n\n## 출력\n\n각 쿼리에 대한 최솟값을 한 줄에 하나씩 출력한다.\n\n## 예제 입력 1\n\n```\n5 3\n3 1 4 1 5\n1 3\n2 5\n1 5\n```\n\n## 예제 출력 1\n\n```\n1\n1\n1\n```",
    difficulty: 6.0,
    timeLimitMs: 3000,
    memoryLimitMb: 256,
    comparisonMode: "exact",
    floatAbsoluteError: null,
    testCases: [
      { input: "5 3\n3 1 4 1 5\n1 3\n2 5\n1 5", expectedOutput: "1\n1\n1", isVisible: true },
      { input: "4 2\n5 4 3 2\n2 4\n1 3", expectedOutput: "2\n3", isVisible: true },
      { input: "3 3\n7 2 9\n1 1\n2 2\n3 3", expectedOutput: "7\n2\n9", isVisible: false },
      { input: "5 2\n10 20 5 30 1\n1 4\n3 5", expectedOutput: "5\n1", isVisible: false },
      { input: "1 1\n42\n1 1", expectedOutput: "42", isVisible: false },
    ],
    tags: ["자료구조", "세그먼트 트리"],
  },

  {
    title: "구간 최댓값 쿼리",
    description: "N개의 수로 이루어진 수열이 있다. M개의 쿼리가 주어지며, 각 쿼리 [L, R]에 대해 L번째부터 R번째 수 중 최댓값을 출력한다.\n\n## 입력\n\n첫째 줄에 N과 M이 주어진다. (1 ≤ N ≤ 100,000, 1 ≤ M ≤ 100,000)\n둘째 줄에 N개의 정수가 공백으로 구분되어 주어진다. (1 ≤ Ai ≤ 10^9)\n다음 M개의 줄에 L과 R이 주어진다. (1 ≤ L ≤ R ≤ N)\n\n## 출력\n\n각 쿼리에 대한 최댓값을 한 줄에 하나씩 출력한다.\n\n## 예제 입력 1\n\n```\n5 3\n3 1 4 1 5\n1 3\n2 5\n1 5\n```\n\n## 예제 출력 1\n\n```\n4\n5\n5\n```",
    difficulty: 6.0,
    timeLimitMs: 3000,
    memoryLimitMb: 256,
    comparisonMode: "exact",
    floatAbsoluteError: null,
    testCases: [
      { input: "5 3\n3 1 4 1 5\n1 3\n2 5\n1 5", expectedOutput: "4\n5\n5", isVisible: true },
      { input: "4 2\n2 4 1 3\n1 3\n2 4", expectedOutput: "4\n4", isVisible: true },
      { input: "3 3\n7 2 9\n1 1\n2 2\n3 3", expectedOutput: "7\n2\n9", isVisible: false },
      { input: "5 2\n10 20 5 30 1\n1 4\n3 5", expectedOutput: "30\n30", isVisible: false },
      { input: "1 1\n42\n1 1", expectedOutput: "42", isVisible: false },
    ],
    tags: ["자료구조", "세그먼트 트리"],
  },

  {
    title: "펜윅 트리 (구간 합)",
    description: "N개의 수로 이루어진 수열이 있다. 두 종류의 연산을 처리한다.\n- 1 i v: i번째 수를 v로 변경 (점 갱신)\n- 2 l r: l번째부터 r번째까지의 합을 출력 (구간 합)\nBIT(Binary Indexed Tree, 펜윅 트리)를 사용하여 구현한다.\n\n## 입력\n\n첫째 줄에 N, M이 주어진다. (1 ≤ N ≤ 1,000,000, 1 ≤ M ≤ 200,000)\n둘째 줄에 N개의 정수가 공백으로 구분되어 주어진다. (각 수 ≤ 10^6)\n다음 M개의 줄에 연산이 주어진다.\n\n## 출력\n\n2번 연산에 대한 결과를 한 줄에 하나씩 출력한다.\n\n## 예제 입력 1\n\n```\n5 3\n1 2 3 4 5\n2 1 5\n1 3 10\n2 1 5\n```\n\n## 예제 출력 1\n\n```\n15\n22\n```",
    difficulty: 6.0,
    timeLimitMs: 3000,
    memoryLimitMb: 256,
    comparisonMode: "exact",
    floatAbsoluteError: null,
    testCases: [
      { input: "5 3\n1 2 3 4 5\n2 1 5\n1 3 10\n2 1 5", expectedOutput: "15\n22", isVisible: true },
      { input: "3 2\n1 1 1\n2 1 3\n1 2 5", expectedOutput: "3", isVisible: true },
      { input: "4 4\n1 2 3 4\n2 2 4\n1 1 10\n2 1 4\n2 3 4", expectedOutput: "9\n19\n7", isVisible: false },
      { input: "1 2\n7\n2 1 1\n1 1 3", expectedOutput: "7", isVisible: false },
      { input: "5 3\n5 4 3 2 1\n2 1 3\n2 2 5\n2 3 5", expectedOutput: "12\n10\n6", isVisible: false },
    ],
    tags: ["자료구조", "세그먼트 트리"],
  },

  {
    title: "역전 수 세기 (BIT)",
    description: "N개의 수로 이루어진 수열에서 역전 쌍(i < j이고 A[i] > A[j])의 수를 구한다. BIT(Binary Indexed Tree)를 이용해 O(N log N)에 해결한다.\n\n## 입력\n\n첫째 줄에 N이 주어진다. (1 ≤ N ≤ 500,000)\n둘째 줄에 N개의 정수가 공백으로 구분되어 주어진다. (1 ≤ Ai ≤ N, 중복 없음)\n\n## 출력\n\n역전 쌍의 수를 출력한다.\n\n## 예제 입력 1\n\n```\n5\n5 3 1 4 2\n```\n\n## 예제 출력 1\n\n```\n7\n```",
    difficulty: 6.5,
    timeLimitMs: 3000,
    memoryLimitMb: 256,
    comparisonMode: "exact",
    floatAbsoluteError: null,
    testCases: [
      { input: "5\n5 3 1 4 2", expectedOutput: "7", isVisible: true },
      { input: "3\n1 2 3", expectedOutput: "0", isVisible: true },
      { input: "3\n3 2 1", expectedOutput: "3", isVisible: false },
      { input: "4\n2 1 4 3", expectedOutput: "2", isVisible: false },
      { input: "5\n2 5 1 3 4", expectedOutput: "4", isVisible: false },
    ],
    tags: ["자료구조", "세그먼트 트리"],
  },

  {
    title: "구간 합 변경 + 구간 쿼리 (Lazy Propagation)",
    description: "N개의 수로 이루어진 수열이 있다. Lazy Propagation을 사용하는 세그먼트 트리로 두 연산을 처리한다.\n- 1 l r v: l번째부터 r번째 수에 모두 v를 더한다\n- 2 l r: l번째부터 r번째 수의 합을 출력한다\n\n## 입력\n\n첫째 줄에 N과 M이 주어진다. (1 ≤ N ≤ 1,000,000, 1 ≤ M ≤ 200,000)\n둘째 줄에 N개의 정수가 공백으로 구분되어 주어진다. (각 수 ≤ 10^6)\n다음 M개의 줄에 연산이 주어진다.\n\n## 출력\n\n2번 연산에 대한 결과를 한 줄에 하나씩 출력한다.\n\n## 예제 입력 1\n\n```\n5 3\n1 2 3 4 5\n1 1 3 10\n2 1 5\n2 2 4\n```\n\n## 예제 출력 1\n\n```\n45\n32\n```",
    difficulty: 7.0,
    timeLimitMs: 5000,
    memoryLimitMb: 256,
    comparisonMode: "exact",
    floatAbsoluteError: null,
    testCases: [
      { input: "5 3\n1 2 3 4 5\n1 1 3 10\n2 1 5\n2 2 4", expectedOutput: "45\n32", isVisible: true },
      { input: "3 2\n1 1 1\n1 1 3 5\n2 1 3", expectedOutput: "18", isVisible: true },
      { input: "4 4\n0 0 0 0\n1 1 4 3\n2 1 4\n1 2 3 2\n2 1 4", expectedOutput: "12\n16", isVisible: false },
      { input: "5 3\n5 5 5 5 5\n1 2 4 10\n2 1 5\n2 2 4", expectedOutput: "55\n45", isVisible: false },
      { input: "1 2\n0\n1 1 1 7\n2 1 1", expectedOutput: "7", isVisible: false },
    ],
    tags: ["자료구조", "세그먼트 트리"],
  },

  {
    title: "K번째 수 (세그먼트 트리)",
    description: "N개의 수와 Q개의 쿼리가 있다. 각 쿼리는 두 가지이다.\n- 1 i v: i번째 수를 v로 변경\n- 2 k: 현재 수열에서 K번째로 작은 수를 출력 (세그먼트 트리의 walk down)\n\n## 입력\n\n첫째 줄에 N과 Q가 주어진다. (1 ≤ N ≤ 100,000, 1 ≤ Q ≤ 100,000)\n둘째 줄에 N개의 정수가 공백으로 구분되어 주어진다. (1 ≤ Ai ≤ 10^9)\n다음 Q개의 줄에 연산이 주어진다.\n\n## 출력\n\n2번 쿼리에 대한 결과를 한 줄에 하나씩 출력한다.\n\n## 예제 입력 1\n\n```\n5 3\n5 3 1 4 2\n2 1\n2 3\n2 5\n```\n\n## 예제 출력 1\n\n```\n1\n3\n5\n```",
    difficulty: 7.0,
    timeLimitMs: 3000,
    memoryLimitMb: 256,
    comparisonMode: "exact",
    floatAbsoluteError: null,
    testCases: [
      { input: "5 3\n5 3 1 4 2\n2 1\n2 3\n2 5", expectedOutput: "1\n3\n5", isVisible: true },
      { input: "3 2\n3 1 2\n2 1\n2 2", expectedOutput: "1\n2", isVisible: true },
      { input: "4 4\n4 3 2 1\n2 2\n1 1 5\n2 2\n2 4", expectedOutput: "2\n2\n4", isVisible: false },
      { input: "5 3\n1 2 3 4 5\n2 3\n1 3 10\n2 3", expectedOutput: "3\n4", isVisible: false },
      { input: "1 1\n7\n2 1", expectedOutput: "7", isVisible: false },
    ],
    tags: ["자료구조", "세그먼트 트리"],
  },

  {
    title: "좌표 압축 + 구간 쿼리",
    description: "N개의 좌표에 대해 각 좌표에 점을 추가하고, 구간 [L, R]에 있는 점의 수를 쿼리한다. 좌표 압축 후 세그먼트 트리를 사용한다.\n- 1 x: 좌표 x에 점 추가\n- 2 l r: 좌표 [l, r] 범위에 있는 점의 수 출력\n\n## 입력\n\n첫째 줄에 쿼리 수 N이 주어진다. (1 ≤ N ≤ 500,000)\n둘째 줄부터 N개의 쿼리가 주어진다. 좌표 범위는 -10^9 이상 10^9 이하이다.\n\n## 출력\n\n2번 쿼리에 대한 결과를 한 줄에 하나씩 출력한다.\n\n## 예제 입력 1\n\n```\n6\n1 1\n1 5\n1 3\n2 1 5\n1 2\n2 2 4\n```\n\n## 예제 출력 1\n\n```\n3\n2\n```",
    difficulty: 7.0,
    timeLimitMs: 3000,
    memoryLimitMb: 256,
    comparisonMode: "exact",
    floatAbsoluteError: null,
    testCases: [
      { input: "6\n1 1\n1 5\n1 3\n2 1 5\n1 2\n2 2 4", expectedOutput: "3\n2", isVisible: true },
      { input: "3\n1 100\n1 200\n2 50 250", expectedOutput: "2", isVisible: true },
      { input: "5\n1 -5\n1 0\n1 5\n2 -5 5\n2 0 5", expectedOutput: "3\n2", isVisible: false },
      { input: "4\n1 10\n2 1 20\n1 20\n2 1 20", expectedOutput: "1\n2", isVisible: false },
      { input: "2\n1 1000000000\n2 -1000000000 1000000000", expectedOutput: "1", isVisible: false },
    ],
    tags: ["자료구조", "세그먼트 트리"],
  },

  // ─── 문자열 알고리즘 (36–45) ─────────────────────────────────────────────────

  {
    title: "문자열 해싱",
    description: "N개의 문자열 중 서로 다른 문자열의 수를 구한다. 해시를 이용하여 처리한다.\n\n## 입력\n\n첫째 줄에 N이 주어진다. (1 ≤ N ≤ 10,000)\n둘째 줄부터 N개의 문자열이 한 줄에 하나씩 주어진다. (각 문자열의 길이 ≤ 500, 소문자 알파벳)\n\n## 출력\n\n서로 다른 문자열의 수를 출력한다.\n\n## 예제 입력 1\n\n```\n5\nabc\ndef\nabc\nghi\ndef\n```\n\n## 예제 출력 1\n\n```\n3\n```",
    difficulty: 5.0,
    timeLimitMs: 2000,
    memoryLimitMb: 256,
    comparisonMode: "exact",
    floatAbsoluteError: null,
    testCases: [
      { input: "5\nabc\ndef\nabc\nghi\ndef", expectedOutput: "3", isVisible: true },
      { input: "3\na\na\na", expectedOutput: "1", isVisible: true },
      { input: "4\ncat\ndog\nbird\ncat", expectedOutput: "3", isVisible: false },
      { input: "3\nabc\nabcd\nabcde", expectedOutput: "3", isVisible: false },
      { input: "5\nhello\nworld\nhello\nworld\nhello", expectedOutput: "2", isVisible: false },
    ],
    tags: ["문자열"],
  },

  {
    title: "KMP 문자열 검색",
    description: "텍스트 T에서 패턴 P가 등장하는 횟수와 시작 위치(1-indexed)를 구한다. KMP 알고리즘을 사용한다.\n\n## 입력\n\n첫째 줄에 텍스트 T가 주어진다. (1 ≤ |T| ≤ 1,000,000)\n둘째 줄에 패턴 P가 주어진다. (1 ≤ |P| ≤ 1,000,000, |P| ≤ |T|)\n\n## 출력\n\n첫째 줄에 패턴이 등장하는 횟수를 출력한다.\n둘째 줄부터 등장하는 시작 위치를 오름차순으로 한 줄에 하나씩 출력한다.\n\n## 예제 입력 1\n\n```\naababcababababcababab\nababab\n```\n\n## 예제 출력 1\n\n```\n2\n7\n13\n```",
    difficulty: 6.0,
    timeLimitMs: 3000,
    memoryLimitMb: 256,
    comparisonMode: "exact",
    floatAbsoluteError: null,
    testCases: [
      { input: "aababcababababcababab\nababab", expectedOutput: "2\n7\n13", isVisible: true },
      { input: "aaaa\naa", expectedOutput: "3\n1\n2\n3", isVisible: true },
      { input: "abcdef\nxyz", expectedOutput: "0", isVisible: false },
      { input: "ababab\nab", expectedOutput: "3\n1\n3\n5", isVisible: false },
      { input: "aaa\naaa", expectedOutput: "1\n1", isVisible: false },
    ],
    tags: ["문자열", "KMP"],
  },

  {
    title: "접미사 배열 (기본)",
    description: "문자열의 모든 접미사를 사전순으로 정렬하여 각 접미사의 시작 인덱스(0-indexed)를 출력한다.\n\n## 입력\n\n첫째 줄에 문자열이 주어진다. (길이 ≤ 10,000, 소문자 알파벳)\n\n## 출력\n\n접미사 배열(사전순 정렬된 접미사들의 시작 인덱스)을 공백으로 구분하여 출력한다.\n\n## 예제 입력 1\n\n```\nbanana\n```\n\n## 예제 출력 1\n\n```\n5 3 1 0 4 2\n```",
    difficulty: 6.5,
    timeLimitMs: 3000,
    memoryLimitMb: 256,
    comparisonMode: "exact",
    floatAbsoluteError: null,
    testCases: [
      { input: "banana", expectedOutput: "5 3 1 0 4 2", isVisible: true },
      { input: "abc", expectedOutput: "0 1 2", isVisible: true },
      { input: "aab", expectedOutput: "0 1 2", isVisible: false },
      { input: "abba", expectedOutput: "3 0 2 1", isVisible: false },
      { input: "aaa", expectedOutput: "2 1 0", isVisible: false },
    ],
    tags: ["문자열"],
  },

  {
    title: "가장 긴 공통 접두사 (LCP)",
    description: "두 문자열이 주어질 때, 두 문자열의 가장 긴 공통 접두사(LCP, Longest Common Prefix)의 길이를 출력한다.\n\n## 입력\n\n첫째 줄에 문자열 A가 주어진다. (1 ≤ |A| ≤ 100,000)\n둘째 줄에 문자열 B가 주어진다. (1 ≤ |B| ≤ 100,000)\n두 문자열은 소문자 알파벳으로 이루어진다.\n\n## 출력\n\n두 문자열의 LCP 길이를 출력한다.\n\n## 예제 입력 1\n\n```\nabcdef\nabcxyz\n```\n\n## 예제 출력 1\n\n```\n3\n```",
    difficulty: 5.0,
    timeLimitMs: 2000,
    memoryLimitMb: 256,
    comparisonMode: "exact",
    floatAbsoluteError: null,
    testCases: [
      { input: "abcdef\nabcxyz", expectedOutput: "3", isVisible: true },
      { input: "abc\nabc", expectedOutput: "3", isVisible: true },
      { input: "abc\nxyz", expectedOutput: "0", isVisible: false },
      { input: "a\nabcde", expectedOutput: "1", isVisible: false },
      { input: "hello\nworld", expectedOutput: "0", isVisible: false },
    ],
    tags: ["문자열"],
  },

  {
    title: "트라이 (기본)",
    description: "N개의 문자열을 삽입하고, M개의 쿼리 문자열이 트라이에 존재하는지 확인한다.\n\n## 입력\n\n첫째 줄에 N이 주어진다. (1 ≤ N ≤ 10,000)\n둘째 줄부터 N개의 문자열이 한 줄에 하나씩 주어진다. (각 길이 ≤ 500, 소문자 알파벳)\n다음 줄에 M이 주어진다. (1 ≤ M ≤ 10,000)\n다음 M개의 줄에 쿼리 문자열이 주어진다.\n\n## 출력\n\n각 쿼리 문자열이 존재하면 \"YES\", 아니면 \"NO\"를 출력한다.\n\n## 예제 입력 1\n\n```\n3\napple\nbanana\ncherry\n4\napple\napp\nbanana\nmango\n```\n\n## 예제 출력 1\n\n```\nYES\nNO\nYES\nNO\n```",
    difficulty: 5.5,
    timeLimitMs: 2000,
    memoryLimitMb: 256,
    comparisonMode: "exact",
    floatAbsoluteError: null,
    testCases: [
      { input: "3\napple\nbanana\ncherry\n4\napple\napp\nbanana\nmango", expectedOutput: "YES\nNO\nYES\nNO", isVisible: true },
      { input: "1\nabc\n1\nabc", expectedOutput: "YES", isVisible: true },
      { input: "2\nhello\nworld\n3\nhello\nhell\nworld", expectedOutput: "YES\nNO\nYES", isVisible: false },
      { input: "1\na\n2\na\nb", expectedOutput: "YES\nNO", isVisible: false },
      { input: "3\nabc\nabd\nabe\n3\nabc\nab\nabd", expectedOutput: "YES\nNO\nYES", isVisible: false },
    ],
    tags: ["자료구조", "트라이"],
  },

  {
    title: "문자열 주기",
    description: "문자열 S의 최소 주기를 구한다. 최소 주기 p란, S[i] = S[i mod p]가 모든 i에 대해 성립하는 가장 작은 양의 정수이다. KMP의 failure function을 이용한다.\n\n## 입력\n\n첫째 줄에 문자열이 주어진다. (1 ≤ 길이 ≤ 1,000,000, 소문자 알파벳)\n\n## 출력\n\n문자열의 최소 주기를 출력한다.\n\n## 예제 입력 1\n\n```\nabababab\n```\n\n## 예제 출력 1\n\n```\n2\n```",
    difficulty: 6.5,
    timeLimitMs: 2000,
    memoryLimitMb: 256,
    comparisonMode: "exact",
    floatAbsoluteError: null,
    testCases: [
      { input: "abababab", expectedOutput: "2", isVisible: true },
      { input: "abcabc", expectedOutput: "3", isVisible: true },
      { input: "aabaa", expectedOutput: "5", isVisible: false },
      { input: "aaaa", expectedOutput: "1", isVisible: false },
      { input: "abcde", expectedOutput: "5", isVisible: false },
    ],
    tags: ["문자열", "KMP"],
  },

  {
    title: "팰린드롬 완성 (KMP)",
    description: "문자열 S의 뒤에 최소 개수의 문자를 추가하여 팰린드롬을 만든다. 추가된 팰린드롬 문자열을 출력한다. KMP 알고리즘 활용.\n\n## 입력\n\n첫째 줄에 문자열 S가 주어진다. (1 ≤ |S| ≤ 1,000,000, 소문자 알파벳)\n\n## 출력\n\n최소 문자를 추가하여 만든 팰린드롬을 출력한다.\n\n## 예제 입력 1\n\n```\nabab\n```\n\n## 예제 출력 1\n\n```\nababa\n```",
    difficulty: 6.5,
    timeLimitMs: 3000,
    memoryLimitMb: 256,
    comparisonMode: "exact",
    floatAbsoluteError: null,
    testCases: [
      { input: "abab", expectedOutput: "ababa", isVisible: true },
      { input: "abc", expectedOutput: "abcba", isVisible: true },
      { input: "aab", expectedOutput: "aabaa", isVisible: false },
      { input: "abba", expectedOutput: "abba", isVisible: false },
      { input: "a", expectedOutput: "a", isVisible: false },
    ],
    tags: ["문자열", "KMP"],
  },

  {
    title: "라빈-카프 해싱",
    description: "텍스트 T에서 패턴 P의 모든 등장 위치(1-indexed)를 라빈-카프(Rabin-Karp) 알고리즘을 이용하여 구한다.\n\n## 입력\n\n첫째 줄에 텍스트 T가 주어진다. (1 ≤ |T| ≤ 1,000,000)\n둘째 줄에 패턴 P가 주어진다. (1 ≤ |P| ≤ 100,000, |P| ≤ |T|)\n두 문자열은 소문자 알파벳으로 이루어진다.\n\n## 출력\n\n첫째 줄에 등장 횟수를 출력한다.\n둘째 줄부터 시작 위치를 오름차순으로 한 줄에 하나씩 출력한다.\n\n## 예제 입력 1\n\n```\nabcababcab\nabc\n```\n\n## 예제 출력 1\n\n```\n2\n1\n6\n```",
    difficulty: 6.0,
    timeLimitMs: 3000,
    memoryLimitMb: 256,
    comparisonMode: "exact",
    floatAbsoluteError: null,
    testCases: [
      { input: "abcababcab\nabc", expectedOutput: "2\n1\n6", isVisible: true },
      { input: "aaa\na", expectedOutput: "3\n1\n2\n3", isVisible: true },
      { input: "hello\nworld", expectedOutput: "0", isVisible: false },
      { input: "abab\nab", expectedOutput: "2\n1\n3", isVisible: false },
      { input: "abcdef\nabcdef", expectedOutput: "1\n1", isVisible: false },
    ],
    tags: ["문자열"],
  },

  {
    title: "자동완성",
    description: "N개의 단어가 있는 사전이 있다. M개의 접두사 쿼리에 대해 해당 접두사로 시작하는 단어의 수를 출력한다. 트라이를 이용한다.\n\n## 입력\n\n첫째 줄에 N이 주어진다. (1 ≤ N ≤ 10,000)\n둘째 줄부터 N개의 단어가 주어진다. (각 길이 ≤ 100, 소문자 알파벳)\n다음 줄에 M이 주어진다. (1 ≤ M ≤ 10,000)\n다음 M개의 줄에 접두사 쿼리가 주어진다.\n\n## 출력\n\n각 쿼리에 대한 결과를 한 줄에 하나씩 출력한다.\n\n## 예제 입력 1\n\n```\n4\napple\napp\napricot\nbanana\n3\nap\napp\nb\n```\n\n## 예제 출력 1\n\n```\n3\n2\n1\n```",
    difficulty: 6.0,
    timeLimitMs: 2000,
    memoryLimitMb: 256,
    comparisonMode: "exact",
    floatAbsoluteError: null,
    testCases: [
      { input: "4\napple\napp\napricot\nbanana\n3\nap\napp\nb", expectedOutput: "3\n2\n1", isVisible: true },
      { input: "2\nhello\nworld\n2\nhello\nhe", expectedOutput: "1\n1", isVisible: true },
      { input: "3\nabc\nabd\nabe\n3\nab\nabc\nac", expectedOutput: "3\n1\n0", isVisible: false },
      { input: "1\na\n2\na\nab", expectedOutput: "1\n0", isVisible: false },
      { input: "3\ncat\ncar\ncake\n2\nca\ncab", expectedOutput: "3\n0", isVisible: false },
    ],
    tags: ["자료구조", "트라이"],
  },

  {
    title: "Z 알고리즘",
    description: "문자열 S에 대해 Z 배열을 구한다. Z[i]는 S와 S[i:]의 가장 긴 공통 접두사의 길이이다. (Z[0] = |S|로 정의)\n\n## 입력\n\n첫째 줄에 문자열 S가 주어진다. (1 ≤ |S| ≤ 200,000, 소문자 알파벳)\n\n## 출력\n\nZ 배열을 공백으로 구분하여 한 줄에 출력한다.\n\n## 예제 입력 1\n\n```\naabxaa\n```\n\n## 예제 출력 1\n\n```\n6 1 0 0 2 1\n```",
    difficulty: 6.5,
    timeLimitMs: 3000,
    memoryLimitMb: 256,
    comparisonMode: "exact",
    floatAbsoluteError: null,
    testCases: [
      { input: "aabxaa", expectedOutput: "6 1 0 0 2 1", isVisible: true },
      { input: "aaaa", expectedOutput: "4 3 2 1", isVisible: true },
      { input: "abcabc", expectedOutput: "6 0 0 3 0 0", isVisible: false },
      { input: "aabaa", expectedOutput: "5 1 0 2 1", isVisible: false },
      { input: "a", expectedOutput: "1", isVisible: false },
    ],
    tags: ["문자열"],
  },

  // ─── 고급 문제 해결 (46–50) ──────────────────────────────────────────────────

  {
    title: "투 포인터 — 부분 합",
    description: "N개의 양의 정수로 이루어진 수열에서, 연속된 부분 배열의 합이 S 이상인 것 중 최소 길이를 구한다. 존재하지 않으면 0을 출력한다.\n\n## 입력\n\n첫째 줄에 N과 S가 주어진다. (1 ≤ N ≤ 100,000, 1 ≤ S ≤ 10^8)\n둘째 줄에 N개의 양의 정수가 공백으로 구분되어 주어진다. (1 ≤ Ai ≤ 10^4)\n\n## 출력\n\n조건을 만족하는 부분 배열의 최소 길이를 출력한다. 없으면 0.\n\n## 예제 입력 1\n\n```\n5 11\n1 2 3 4 5\n```\n\n## 예제 출력 1\n\n```\n3\n```",
    difficulty: 5.5,
    timeLimitMs: 2000,
    memoryLimitMb: 256,
    comparisonMode: "exact",
    floatAbsoluteError: null,
    testCases: [
      { input: "5 11\n1 2 3 4 5", expectedOutput: "3", isVisible: true },
      { input: "4 10\n1 2 3 4", expectedOutput: "4", isVisible: true },
      { input: "5 100\n1 2 3 4 5", expectedOutput: "0", isVisible: false },
      { input: "3 4\n1 4 2", expectedOutput: "1", isVisible: false },
      { input: "5 15\n1 2 3 4 5", expectedOutput: "5", isVisible: false },
    ],
    tags: ["투 포인터"],
  },

  {
    title: "투 포인터 — 두 수의 합",
    description: "오름차순으로 정렬된 N개의 정수에서 합이 X인 서로 다른 두 원소 쌍의 개수를 구한다.\n\n## 입력\n\n첫째 줄에 N과 X가 주어진다. (1 ≤ N ≤ 100,000, 1 ≤ X ≤ 2×10^9)\n둘째 줄에 오름차순으로 정렬된 N개의 정수가 공백으로 구분되어 주어진다. (1 ≤ Ai ≤ 10^9)\n\n## 출력\n\n합이 X인 쌍의 수를 출력한다.\n\n## 예제 입력 1\n\n```\n6 9\n1 2 3 6 7 8\n```\n\n## 예제 출력 1\n\n```\n2\n```",
    difficulty: 5.0,
    timeLimitMs: 2000,
    memoryLimitMb: 256,
    comparisonMode: "exact",
    floatAbsoluteError: null,
    testCases: [
      { input: "6 9\n1 2 3 6 7 8", expectedOutput: "2", isVisible: true },
      { input: "3 5\n1 2 3", expectedOutput: "1", isVisible: true },
      { input: "4 10\n1 2 3 4", expectedOutput: "0", isVisible: false },
      { input: "5 6\n1 2 3 4 5", expectedOutput: "2", isVisible: false },
      { input: "4 7\n1 3 5 7", expectedOutput: "1", isVisible: false },
    ],
    tags: ["투 포인터"],
  },

  {
    title: "좌표 압축",
    description: "N개의 정수가 주어질 때, 각 정수를 0부터 시작하는 상대적인 순위(압축된 값)로 변환한다. 같은 값이면 같은 압축 값을 가진다.\n\n## 입력\n\n첫째 줄에 N이 주어진다. (1 ≤ N ≤ 1,000,000)\n둘째 줄에 N개의 정수가 공백으로 구분되어 주어진다. (−10^9 ≤ Ai ≤ 10^9)\n\n## 출력\n\n각 원소의 압축된 값을 공백으로 구분하여 출력한다.\n\n## 예제 입력 1\n\n```\n5\n2 4 -10 4 -10\n```\n\n## 예제 출력 1\n\n```\n1 2 0 2 0\n```",
    difficulty: 5.0,
    timeLimitMs: 3000,
    memoryLimitMb: 256,
    comparisonMode: "exact",
    floatAbsoluteError: null,
    testCases: [
      { input: "5\n2 4 -10 4 -10", expectedOutput: "1 2 0 2 0", isVisible: true },
      { input: "3\n10 20 30", expectedOutput: "0 1 2", isVisible: true },
      { input: "4\n5 5 5 5", expectedOutput: "0 0 0 0", isVisible: false },
      { input: "5\n-5 -1 0 1 5", expectedOutput: "0 1 2 3 4", isVisible: false },
      { input: "4\n1000000000 -1000000000 0 0", expectedOutput: "2 0 1 1", isVisible: false },
    ],
    tags: ["정렬", "구현"],
  },

  {
    title: "Mo's 알고리즘 (기본)",
    description: "N개의 정수로 이루어진 수열과 Q개의 쿼리가 있다. 각 쿼리 [L, R]에 대해 A[L], A[L+1], ..., A[R] 중 서로 다른 수의 개수를 구한다. Mo's 알고리즘을 이용하여 오프라인으로 처리한다.\n\n## 입력\n\n첫째 줄에 N과 Q가 주어진다. (1 ≤ N, Q ≤ 100,000)\n둘째 줄에 N개의 정수가 공백으로 구분되어 주어진다. (1 ≤ Ai ≤ 1,000,000)\n다음 Q개의 줄에 L과 R이 주어진다. (1 ≤ L ≤ R ≤ N)\n\n## 출력\n\n각 쿼리에 대한 답을 입력 순서대로 한 줄에 하나씩 출력한다.\n\n## 예제 입력 1\n\n```\n6 3\n1 2 1 3 2 1\n1 3\n2 5\n3 6\n```\n\n## 예제 출력 1\n\n```\n2\n3\n3\n```",
    difficulty: 7.0,
    timeLimitMs: 5000,
    memoryLimitMb: 256,
    comparisonMode: "exact",
    floatAbsoluteError: null,
    testCases: [
      { input: "6 3\n1 2 1 3 2 1\n1 3\n2 5\n3 6", expectedOutput: "2\n3\n3", isVisible: true },
      { input: "3 2\n1 1 1\n1 3\n2 2", expectedOutput: "1\n1", isVisible: true },
      { input: "5 3\n1 2 3 4 5\n1 5\n2 4\n1 1", expectedOutput: "5\n3\n1", isVisible: false },
      { input: "4 2\n1 2 1 2\n1 4\n2 3", expectedOutput: "2\n2", isVisible: false },
      { input: "5 4\n1 1 2 2 3\n1 2\n3 4\n1 4\n2 5", expectedOutput: "1\n1\n2\n3", isVisible: false },
    ],
    tags: ["자료구조"],
  },

  {
    title: "평면 스위핑 — 선분 교차",
    description: "N개의 수평 또는 수직 선분이 주어진다. 이 선분들 사이의 교차점의 수를 구한다. 수평 선분과 수직 선분만 고려하며, 같은 방향의 선분끼리는 교차하지 않는다고 가정한다. 평면 스위핑과 세그먼트 트리를 이용한다.\n\n## 입력\n\n첫째 줄에 선분의 수 N이 주어진다. (1 ≤ N ≤ 100,000)\n둘째 줄부터 N개의 줄에 선분의 양 끝점 x1 y1 x2 y2가 주어진다. (x1 ≤ x2, y1 ≤ y2, 좌표 범위 −10^9 이상 10^9 이하)\n수평 선분은 y1 = y2, 수직 선분은 x1 = x2이다.\n\n## 출력\n\n교차점의 수를 출력한다.\n\n## 예제 입력 1\n\n```\n4\n0 1 2 1\n1 0 1 2\n3 0 3 2\n2 1 4 1\n```\n\n## 예제 출력 1\n\n```\n2\n```",
    difficulty: 7.0,
    timeLimitMs: 5000,
    memoryLimitMb: 256,
    comparisonMode: "exact",
    floatAbsoluteError: null,
    testCases: [
      { input: "4\n0 1 2 1\n1 0 1 2\n3 0 3 2\n2 1 4 1", expectedOutput: "2", isVisible: true },
      { input: "2\n0 0 2 0\n1 -1 1 1", expectedOutput: "1", isVisible: true },
      { input: "2\n0 0 2 0\n3 -1 3 1", expectedOutput: "0", isVisible: false },
      { input: "3\n0 1 4 1\n1 0 1 2\n3 0 3 2", expectedOutput: "2", isVisible: false },
      { input: "3\n0 0 10 0\n2 -1 2 1\n5 -1 5 1", expectedOutput: "2", isVisible: false },
    ],
    tags: ["자료구조", "세그먼트 트리"],
  },
];
