FROM alpine:latest

RUN apk add --no-cache gcc g++ musl-dev --repository=https://dl-cdn.alpinelinux.org/alpine/edge/main && \
    adduser -D -s /bin/false judge && \
    mkdir -p /workspace && \
    chown judge:judge /workspace

WORKDIR /workspace

USER judge
