FROM alpine:3.21

RUN apk add --no-cache gcc musl-dev git make && \
    git clone --depth 1 https://github.com/vlang/v /opt/vlang && \
    cd /opt/vlang && make && \
    ln -s /opt/vlang/v /usr/local/bin/v && \
    adduser -D -s /bin/false judge && \
    mkdir -p /workspace && \
    chown judge:judge /workspace

WORKDIR /workspace
USER judge
