FROM alpine:3.21

RUN apk add --no-cache clang clang-extra-tools libc++-dev musl-dev llvm && \
    adduser -D -s /bin/false judge && \
    mkdir -p /workspace && chown judge:judge /workspace

WORKDIR /workspace
USER judge
