/** Built-in role names. Custom roles use arbitrary strings validated at runtime. */
export type BuiltinUserRole = "super_admin" | "admin" | "instructor" | "student";

/**
 * UserRole is kept as the 4-value union for backward compatibility.
 * Custom roles are validated at runtime via the capability cache.
 * Use `string` in function signatures that need to accept custom roles.
 */
export type UserRole = BuiltinUserRole;
export type ProblemVisibility = "public" | "private" | "hidden";
export type AssignmentVisibility = "public" | "private";
export type ProblemType = "auto" | "manual";
export type PlatformMode = "homework" | "exam" | "contest" | "recruiting";
export type SubmissionStatus =
  | "pending"
  | "queued"
  | "judging"
  | "accepted"
  | "wrong_answer"
  | "time_limit"
  | "memory_limit"
  | "runtime_error"
  | "compile_error"
  | "submitted";
export type ExamMode = "none" | "scheduled" | "windowed";
export type ScoringModel = "ioi" | "icpc";
export type Language =
  | "b"
  | "c17"
  | "c23"
  | "cpp20"
  | "cpp23"
  | "cpp26"
  | "java"
  | "python"
  | "pypy"
  | "javascript"
  | "kotlin"
  | "typescript"
  | "plaintext"
  | "verilog"
  | "systemverilog"
  | "vhdl"
  | "rust"
  | "go"
  | "swift"
  | "csharp"
  | "r"
  | "perl"
  | "php"
  | "ruby"
  | "lua"
  | "haskell"
  | "dart"
  | "zig"
  | "nim"
  | "ocaml"
  | "elixir"
  | "julia"
  | "d"
  | "racket"
  | "vlang"
  | "c99"
  | "c89"
  | "fortran"
  | "pascal"
  | "brainfuck"
  | "cobol"
  | "clang_c23"
  | "clang_cpp23"
  | "clang_cpp26"
  | "scala"
  | "erlang"
  | "commonlisp"
  | "bash"
  | "befunge"
  | "aheui"
  | "hyeong"
  | "whitespace"
  | "ada"
  | "clojure"
  | "prolog"
  | "tcl"
  | "awk"
  | "scheme"
  | "groovy"
  | "octave"
  | "crystal"
  | "powershell"
  | "postscript"
  | "delphi"
  | "fsharp"
  | "apl"
  | "freebasic"
  | "smalltalk"
  | "sed"
  | "dc"
  | "coffeescript"
  | "llvm_ir"
  | "vbnet"
  | "nasm"
  | "bqn"
  | "lolcode"
  | "forth"
  | "algol68"
  | "umjunsik"
  | "haxe"
  | "raku"

  | "shakespeare"
  | "snobol4"
  | "icon"
  | "uiua"
  | "odin"
  | "objective_c"
  | "deno_js"
  | "deno_ts"
  | "bun_js"
  | "bun_ts"
  | "gleam"
  | "sml"
  | "fennel"
  | "flix"
  | "micropython"
  | "squirrel"
  | "rexx"
  | "hy"
  | "arturo"
  | "janet"
  | "c3"
  | "vala"
  | "nelua"
  | "hare"
  | "koka"
  | "lean"
  | "picat"
  | "mercury"
  | "wat"
  | "purescript"
  | "modula2"
  | "factor"
  | "spark"
  | "minizinc"
  | "curry"
  | "clean"
  | "carp"
  | "grain"
  | "pony"
  | "moonbit"
  | "chapel"
  | "idris2"
  | "rescript"
  | "elm";
