import type { Language } from "@/types";

export const JUDGE_TOOLCHAIN_VERSIONS = {
  go: "1.26.1",
  java: "25.0.2",
  nodejs: "24.14.0",
  kotlin: "2.3.10",
  python: "3.14.3",
  rust: "1.94.0",
  swift: "6.2.4",
  typescript: "5.9.3",
  mono: "6.12",
  r: "4.5",
  perl: "5.40",
  php: "8.4",
  ruby: "3.4",
  lua: "5.4",
  haskell: "9.4",
  dart: "3.8",
  zig: "0.13",
  nim: "2.2",
  ocaml: "4.14",
  elixir: "1.18",
  julia: "1.12",
  d: "1.39",
  racket: "8.10",
  vlang: "0.5",
  fortran: "14",
  fpc: "3.2",
  gnucobol: "3.2",
  clang: "18",
  scala: "3.5",
  erlang: "27",
  sbcl: "2.5",
  bash: "5.2",
  gnat: "14",
  clojure: "1.12",
  swiprolog: "9",
  tcl: "8.6",
  gawk: "5",
  chicken: "5",
  groovy: "4.0",
  octave: "9",
  crystal: "1.14",
  powershell: "7.5",
  ghostscript: "10",
} as const;

export interface JudgeLanguageDefinition {
  language: Language;
  displayName: string;
  standard: string | null;
  extension: string;
  dockerImage: string;
  compiler: string | null;
  compileCommand: string[] | null;
  runCommand: string[];
}

/** Human-readable base OS / toolchain description for each Docker judge image. */
export const DOCKER_IMAGE_RUNTIME_INFO: Record<string, string> = {
  "judge-cpp:latest": `Alpine 3.21 / GCC ${JUDGE_TOOLCHAIN_VERSIONS.fortran}`,
  "judge-clang:latest": `Alpine 3.21 / Clang ${JUDGE_TOOLCHAIN_VERSIONS.clang}`,
  "judge-python:latest": `Debian Bookworm / CPython ${JUDGE_TOOLCHAIN_VERSIONS.python}`,
  "judge-node:latest": `Debian Bookworm / Node.js ${JUDGE_TOOLCHAIN_VERSIONS.nodejs}`,
  "judge-jvm:latest": `Ubuntu Noble / Temurin ${JUDGE_TOOLCHAIN_VERSIONS.java} + Kotlin ${JUDGE_TOOLCHAIN_VERSIONS.kotlin}`,
  "judge-rust:latest": `Debian Bookworm / Rust ${JUDGE_TOOLCHAIN_VERSIONS.rust}`,
  "judge-go:latest": `Debian Bookworm / Go ${JUDGE_TOOLCHAIN_VERSIONS.go}`,
  "judge-swift:latest": `Ubuntu Noble / Swift ${JUDGE_TOOLCHAIN_VERSIONS.swift}`,
  "judge-csharp:latest": `Mono ${JUDGE_TOOLCHAIN_VERSIONS.mono}`,
  "judge-r:latest": `R ${JUDGE_TOOLCHAIN_VERSIONS.r}`,
  "judge-perl:latest": `Debian Bookworm / Perl ${JUDGE_TOOLCHAIN_VERSIONS.perl}`,
  "judge-php:latest": `Debian Bookworm / PHP ${JUDGE_TOOLCHAIN_VERSIONS.php}`,
  "judge-ruby:latest": `Alpine 3.21 / Ruby ${JUDGE_TOOLCHAIN_VERSIONS.ruby}`,
  "judge-lua:latest": `Alpine 3.21 / Lua ${JUDGE_TOOLCHAIN_VERSIONS.lua}`,
  "judge-haskell:latest": `Debian Bookworm / GHC ${JUDGE_TOOLCHAIN_VERSIONS.haskell}`,
  "judge-dart:latest": `Debian Bookworm / Dart ${JUDGE_TOOLCHAIN_VERSIONS.dart}`,
  "judge-zig:latest": `Alpine 3.21 / Zig ${JUDGE_TOOLCHAIN_VERSIONS.zig}`,
  "judge-nim:latest": `Alpine 3.21 / Nim ${JUDGE_TOOLCHAIN_VERSIONS.nim}`,
  "judge-ocaml:latest": `Alpine 3.21 / OCaml ${JUDGE_TOOLCHAIN_VERSIONS.ocaml}`,
  "judge-elixir:latest": `Debian Bookworm / Elixir ${JUDGE_TOOLCHAIN_VERSIONS.elixir}`,
  "judge-julia:latest": `Debian Bookworm / Julia ${JUDGE_TOOLCHAIN_VERSIONS.julia}`,
  "judge-d:latest": `Ubuntu Noble / LDC2 ${JUDGE_TOOLCHAIN_VERSIONS.d}`,
  "judge-racket:latest": `Debian Bookworm / Racket ${JUDGE_TOOLCHAIN_VERSIONS.racket}`,
  "judge-v:latest": `Alpine 3.21 / V ${JUDGE_TOOLCHAIN_VERSIONS.vlang}`,
  "judge-fortran:latest": `Debian Bookworm / GFortran ${JUDGE_TOOLCHAIN_VERSIONS.fortran}`,
  "judge-pascal:latest": `Debian Bookworm / FPC ${JUDGE_TOOLCHAIN_VERSIONS.fpc}`,
  "judge-brainfuck:latest": "Debian Bookworm / beef interpreter",
  "judge-cobol:latest": `Debian Bookworm / GnuCOBOL ${JUDGE_TOOLCHAIN_VERSIONS.gnucobol}`,
  "judge-scala:latest": `Ubuntu Noble / Scala ${JUDGE_TOOLCHAIN_VERSIONS.scala}`,
  "judge-erlang:latest": `Debian Bookworm / OTP ${JUDGE_TOOLCHAIN_VERSIONS.erlang}`,
  "judge-commonlisp:latest": `Debian Bookworm / SBCL ${JUDGE_TOOLCHAIN_VERSIONS.sbcl}`,
  "judge-bash:latest": `Debian Bookworm / Bash ${JUDGE_TOOLCHAIN_VERSIONS.bash}`,
  "judge-esoteric:latest": "Debian Bookworm / Befunge-93 + Aheui (PyPI) + Hyeong (Rust) + Whitespace (Python)",
  "judge-ada:latest": `Debian Bookworm / GNAT (GCC ${JUDGE_TOOLCHAIN_VERSIONS.gnat})`,
  "judge-clojure:latest": `Ubuntu Noble / Clojure ${JUDGE_TOOLCHAIN_VERSIONS.clojure} / Temurin ${JUDGE_TOOLCHAIN_VERSIONS.java}`,
  "judge-prolog:latest": `Debian Bookworm / SWI-Prolog ${JUDGE_TOOLCHAIN_VERSIONS.swiprolog}`,
  "judge-tcl:latest": `Alpine 3.21 / Tcl ${JUDGE_TOOLCHAIN_VERSIONS.tcl}`,
  "judge-awk:latest": `Alpine 3.21 / GNU AWK ${JUDGE_TOOLCHAIN_VERSIONS.gawk}`,
  "judge-scheme:latest": `Debian Bookworm / Chicken Scheme ${JUDGE_TOOLCHAIN_VERSIONS.chicken}`,
  "judge-groovy:latest": `Ubuntu Noble / Groovy ${JUDGE_TOOLCHAIN_VERSIONS.groovy} / Temurin ${JUDGE_TOOLCHAIN_VERSIONS.java}`,
  "judge-octave:latest": `Debian Bookworm / GNU Octave ${JUDGE_TOOLCHAIN_VERSIONS.octave}`,
  "judge-crystal:latest": `Debian Bookworm / Crystal ${JUDGE_TOOLCHAIN_VERSIONS.crystal}`,
  "judge-powershell:latest": `Debian Bookworm / PowerShell ${JUDGE_TOOLCHAIN_VERSIONS.powershell}`,
  "judge-postscript:latest": `Debian Bookworm / Ghostscript ${JUDGE_TOOLCHAIN_VERSIONS.ghostscript}`,
};

export function getDockerImageRuntimeInfo(dockerImage: string): string {
  return DOCKER_IMAGE_RUNTIME_INFO[dockerImage] ?? dockerImage;
}

export const JUDGE_LANGUAGE_CONFIGS: Record<Language, JudgeLanguageDefinition> = {
  c17: {
    language: "c17",
    displayName: "C",
    standard: "C17",
    extension: ".c",
    dockerImage: "judge-cpp:latest",
    compiler: "GCC (gcc)",
    compileCommand: ["gcc", "-O2", "-std=c17", "-o", "/workspace/solution", "/workspace/solution.c", "-lm"],
    runCommand: ["/workspace/solution"],
  },
  c23: {
    language: "c23",
    displayName: "C",
    standard: "C23",
    extension: ".c",
    dockerImage: "judge-cpp:latest",
    compiler: "GCC (gcc)",
    compileCommand: ["gcc", "-O2", "-std=c23", "-o", "/workspace/solution", "/workspace/solution.c", "-lm"],
    runCommand: ["/workspace/solution"],
  },
  cpp20: {
    language: "cpp20",
    displayName: "C++",
    standard: "C++20",
    extension: ".cpp",
    dockerImage: "judge-cpp:latest",
    compiler: "GCC (g++)",
    compileCommand: ["g++", "-O2", "-std=c++20", "-o", "/workspace/solution", "/workspace/solution.cpp"],
    runCommand: ["/workspace/solution"],
  },
  cpp23: {
    language: "cpp23",
    displayName: "C++",
    standard: "C++23",
    extension: ".cpp",
    dockerImage: "judge-cpp:latest",
    compiler: "GCC (g++)",
    compileCommand: ["g++", "-O2", "-std=c++23", "-o", "/workspace/solution", "/workspace/solution.cpp"],
    runCommand: ["/workspace/solution"],
  },
  java: {
    language: "java",
    displayName: "Java",
    standard: "25",
    extension: ".java",
    dockerImage: "judge-jvm:latest",
    compiler: `Eclipse Temurin ${JUDGE_TOOLCHAIN_VERSIONS.java} (javac/java)`,
    compileCommand: [
      "sh",
      "-c",
      "export JAVA_TOOL_OPTIONS='-Djava.io.tmpdir=/workspace' && mkdir -p /workspace/out && cp /workspace/solution.java /workspace/Main.java && javac --release 25 -encoding UTF-8 -d /workspace/out /workspace/Main.java",
    ],
    runCommand: ["java", "-Djava.io.tmpdir=/workspace", "-cp", "/workspace/out", "Main"],
  },
  python: {
    language: "python",
    displayName: "Python",
    standard: "3.14",
    extension: ".py",
    dockerImage: "judge-python:latest",
    compiler: `Python ${JUDGE_TOOLCHAIN_VERSIONS.python}`,
    compileCommand: null,
    runCommand: ["python3", "/workspace/solution.py"],
  },
  javascript: {
    language: "javascript",
    displayName: "JavaScript",
    standard: "Node.js 24",
    extension: ".js",
    dockerImage: "judge-node:latest",
    compiler: `Node.js ${JUDGE_TOOLCHAIN_VERSIONS.nodejs} (LTS)`,
    compileCommand: null,
    runCommand: ["node", "/workspace/solution.js"],
  },
  typescript: {
    language: "typescript",
    displayName: "TypeScript",
    standard: "TS 5.9",
    extension: ".ts",
    dockerImage: "judge-node:latest",
    compiler: `TypeScript ${JUDGE_TOOLCHAIN_VERSIONS.typescript} (tsc) / Node.js ${JUDGE_TOOLCHAIN_VERSIONS.nodejs}`,
    compileCommand: [
      "tsc",
      "--pretty",
      "false",
      "--strict",
      "--skipLibCheck",
      "--types",
      "node",
      "--typeRoots",
      "/usr/local/lib/node_modules/@types",
      "--target",
      "ES2024",
      "--module",
      "commonjs",
      "--outDir",
      "/workspace/dist",
      "/workspace/solution.ts",
    ],
    runCommand: ["node", "/workspace/dist/solution.js"],
  },
  kotlin: {
    language: "kotlin",
    displayName: "Kotlin",
    standard: "2.3",
    extension: ".kt",
    dockerImage: "judge-jvm:latest",
    compiler: `Kotlin ${JUDGE_TOOLCHAIN_VERSIONS.kotlin} / Eclipse Temurin ${JUDGE_TOOLCHAIN_VERSIONS.java}`,
    compileCommand: [
      "kotlinc",
      "-J-Djava.io.tmpdir=/workspace",
      "/workspace/solution.kt",
      "-include-runtime",
      "-d",
      "/workspace/solution.jar",
    ],
    runCommand: ["java", "-Djava.io.tmpdir=/workspace", "-jar", "/workspace/solution.jar"],
  },
  rust: {
    language: "rust",
    displayName: "Rust",
    standard: "1.94",
    extension: ".rs",
    dockerImage: "judge-rust:latest",
    compiler: `Rust ${JUDGE_TOOLCHAIN_VERSIONS.rust} (rustc)`,
    compileCommand: ["rustc", "-O", "-o", "/workspace/solution", "/workspace/solution.rs"],
    runCommand: ["/workspace/solution"],
  },
  go: {
    language: "go",
    displayName: "Go",
    standard: "1.26",
    extension: ".go",
    dockerImage: "judge-go:latest",
    compiler: `Go ${JUDGE_TOOLCHAIN_VERSIONS.go}`,
    compileCommand: ["go", "build", "-o", "/workspace/solution", "/workspace/solution.go"],
    runCommand: ["/workspace/solution"],
  },
  swift: {
    language: "swift",
    displayName: "Swift",
    standard: "6.2",
    extension: ".swift",
    dockerImage: "judge-swift:latest",
    compiler: `Swift ${JUDGE_TOOLCHAIN_VERSIONS.swift}`,
    compileCommand: [
      "swiftc",
      "-O",
      "-module-cache-path",
      "/tmp/swift-module-cache",
      "-o",
      "/workspace/solution",
      "/workspace/solution.swift",
    ],
    runCommand: ["/workspace/solution"],
  },
  csharp: {
    language: "csharp",
    displayName: "C#",
    standard: "Mono 6",
    extension: ".cs",
    dockerImage: "judge-csharp:latest",
    compiler: `Mono ${JUDGE_TOOLCHAIN_VERSIONS.mono} (mcs)`,
    compileCommand: ["sh", "-c", "HOME=/tmp mcs -optimize+ -out:/workspace/solution.exe /workspace/solution.cs"],
    runCommand: ["sh", "-c", "HOME=/tmp mono /workspace/solution.exe"],
  },
  r: {
    language: "r",
    displayName: "R",
    standard: "4.5",
    extension: ".r",
    dockerImage: "judge-r:latest",
    compiler: `R ${JUDGE_TOOLCHAIN_VERSIONS.r}`,
    compileCommand: null,
    runCommand: ["Rscript", "/workspace/solution.r"],
  },
  perl: {
    language: "perl",
    displayName: "Perl",
    standard: "5.40",
    extension: ".pl",
    dockerImage: "judge-perl:latest",
    compiler: `Perl ${JUDGE_TOOLCHAIN_VERSIONS.perl}`,
    compileCommand: null,
    runCommand: ["perl", "/workspace/solution.pl"],
  },
  php: {
    language: "php",
    displayName: "PHP",
    standard: "8.4",
    extension: ".php",
    dockerImage: "judge-php:latest",
    compiler: `PHP ${JUDGE_TOOLCHAIN_VERSIONS.php}`,
    compileCommand: null,
    runCommand: ["php", "/workspace/solution.php"],
  },
  ruby: {
    language: "ruby",
    displayName: "Ruby",
    standard: "3.4",
    extension: ".rb",
    dockerImage: "judge-ruby:latest",
    compiler: `Ruby ${JUDGE_TOOLCHAIN_VERSIONS.ruby}`,
    compileCommand: null,
    runCommand: ["ruby", "/workspace/solution.rb"],
  },
  lua: {
    language: "lua",
    displayName: "Lua",
    standard: "5.4",
    extension: ".lua",
    dockerImage: "judge-lua:latest",
    compiler: `Lua ${JUDGE_TOOLCHAIN_VERSIONS.lua}`,
    compileCommand: null,
    runCommand: ["lua5.4", "/workspace/solution.lua"],
  },
  haskell: {
    language: "haskell",
    displayName: "Haskell",
    standard: "GHC 9.4",
    extension: ".hs",
    dockerImage: "judge-haskell:latest",
    compiler: `GHC ${JUDGE_TOOLCHAIN_VERSIONS.haskell}`,
    compileCommand: ["ghc", "-O2", "-o", "/workspace/solution", "/workspace/solution.hs"],
    runCommand: ["/workspace/solution"],
  },
  dart: {
    language: "dart",
    displayName: "Dart",
    standard: "3.8",
    extension: ".dart",
    dockerImage: "judge-dart:latest",
    compiler: `Dart ${JUDGE_TOOLCHAIN_VERSIONS.dart}`,
    compileCommand: ["sh", "-c", "HOME=/tmp dart compile exe /workspace/solution.dart -o /workspace/solution"],
    runCommand: ["/workspace/solution"],
  },
  zig: {
    language: "zig",
    displayName: "Zig",
    standard: "0.13",
    extension: ".zig",
    dockerImage: "judge-zig:latest",
    compiler: `Zig ${JUDGE_TOOLCHAIN_VERSIONS.zig}`,
    compileCommand: ["sh", "-c", "zig build-exe --cache-dir /tmp/zig-cache --global-cache-dir /tmp/zig-global -femit-binary=/workspace/solution /workspace/solution.zig -O ReleaseSafe"],
    runCommand: ["/workspace/solution"],
  },
  nim: {
    language: "nim",
    displayName: "Nim",
    standard: "2.2",
    extension: ".nim",
    dockerImage: "judge-nim:latest",
    compiler: `Nim ${JUDGE_TOOLCHAIN_VERSIONS.nim}`,
    compileCommand: ["sh", "-c", "mkdir -p /tmp/nimcache && nim compile --opt:speed -d:release --nimcache:/tmp/nimcache --out:/workspace/solution /workspace/solution.nim"],
    runCommand: ["/workspace/solution"],
  },
  ocaml: {
    language: "ocaml",
    displayName: "OCaml",
    standard: "4.14",
    extension: ".ml",
    dockerImage: "judge-ocaml:latest",
    compiler: `OCaml ${JUDGE_TOOLCHAIN_VERSIONS.ocaml}`,
    compileCommand: ["ocamlfind", "ocamlopt", "-package", "str", "-linkpkg", "-O2", "-o", "/workspace/solution", "/workspace/solution.ml"],
    runCommand: ["/workspace/solution"],
  },
  elixir: {
    language: "elixir",
    displayName: "Elixir",
    standard: "1.18",
    extension: ".exs",
    dockerImage: "judge-elixir:latest",
    compiler: `Elixir ${JUDGE_TOOLCHAIN_VERSIONS.elixir}`,
    compileCommand: null,
    runCommand: ["sh", "-c", "HOME=/tmp elixir /workspace/solution.exs"],
  },
  julia: {
    language: "julia",
    displayName: "Julia",
    standard: "1.12",
    extension: ".jl",
    dockerImage: "judge-julia:latest",
    compiler: `Julia ${JUDGE_TOOLCHAIN_VERSIONS.julia}`,
    compileCommand: null,
    runCommand: ["julia", "/workspace/solution.jl"],
  },
  d: {
    language: "d",
    displayName: "D",
    standard: "LDC2",
    extension: ".d",
    dockerImage: "judge-d:latest",
    compiler: `LDC2 ${JUDGE_TOOLCHAIN_VERSIONS.d}`,
    compileCommand: ["ldc2", "-O2", "-of=/workspace/solution", "/workspace/solution.d"],
    runCommand: ["/workspace/solution"],
  },
  racket: {
    language: "racket",
    displayName: "Racket",
    standard: "8.10",
    extension: ".rkt",
    dockerImage: "judge-racket:latest",
    compiler: `Racket ${JUDGE_TOOLCHAIN_VERSIONS.racket}`,
    compileCommand: null,
    runCommand: ["racket", "/workspace/solution.rkt"],
  },
  vlang: {
    language: "vlang",
    displayName: "V",
    standard: "0.5",
    extension: ".v",
    dockerImage: "judge-v:latest",
    compiler: `V ${JUDGE_TOOLCHAIN_VERSIONS.vlang}`,
    compileCommand: ["v", "-prod", "-o", "/workspace/solution", "/workspace/solution.v"],
    runCommand: ["/workspace/solution"],
  },
  c99: {
    language: "c99",
    displayName: "C",
    standard: "C99",
    extension: ".c",
    dockerImage: "judge-cpp:latest",
    compiler: "GCC (gcc)",
    compileCommand: ["gcc", "-O2", "-std=c99", "-o", "/workspace/solution", "/workspace/solution.c", "-lm"],
    runCommand: ["/workspace/solution"],
  },
  c89: {
    language: "c89",
    displayName: "C",
    standard: "ANSI C (C89)",
    extension: ".c",
    dockerImage: "judge-cpp:latest",
    compiler: "GCC (gcc)",
    compileCommand: ["gcc", "-O2", "-std=c89", "-o", "/workspace/solution", "/workspace/solution.c", "-lm"],
    runCommand: ["/workspace/solution"],
  },
  fortran: {
    language: "fortran",
    displayName: "Fortran",
    standard: "Fortran 2018",
    extension: ".f90",
    dockerImage: "judge-fortran:latest",
    compiler: `GFortran ${JUDGE_TOOLCHAIN_VERSIONS.fortran}`,
    compileCommand: ["gfortran", "-O2", "-std=f2018", "-o", "/workspace/solution", "/workspace/solution.f90"],
    runCommand: ["/workspace/solution"],
  },
  pascal: {
    language: "pascal",
    displayName: "Pascal",
    standard: "Free Pascal 3.2",
    extension: ".pas",
    dockerImage: "judge-pascal:latest",
    compiler: `Free Pascal ${JUDGE_TOOLCHAIN_VERSIONS.fpc}`,
    compileCommand: ["fpc", "-O2", "-o/workspace/solution", "/workspace/solution.pas"],
    runCommand: ["/workspace/solution"],
  },
  brainfuck: {
    language: "brainfuck",
    displayName: "Brainfuck",
    standard: null,
    extension: ".bf",
    dockerImage: "judge-brainfuck:latest",
    compiler: "bf interpreter",
    compileCommand: null,
    runCommand: ["beef", "/workspace/solution.bf"],
  },
  cobol: {
    language: "cobol",
    displayName: "COBOL",
    standard: "GnuCOBOL 3.2",
    extension: ".cob",
    dockerImage: "judge-cobol:latest",
    compiler: `GnuCOBOL ${JUDGE_TOOLCHAIN_VERSIONS.gnucobol}`,
    compileCommand: ["cobc", "-x", "-O2", "-o", "/workspace/solution", "/workspace/solution.cob"],
    runCommand: ["/workspace/solution"],
  },
  clang_c23: {
    language: "clang_c23",
    displayName: "C (Clang)",
    standard: "C23",
    extension: ".c",
    dockerImage: "judge-clang:latest",
    compiler: `Clang ${JUDGE_TOOLCHAIN_VERSIONS.clang}`,
    compileCommand: ["clang", "-O2", "-std=c23", "-o", "/workspace/solution", "/workspace/solution.c", "-lm"],
    runCommand: ["/workspace/solution"],
  },
  clang_cpp23: {
    language: "clang_cpp23",
    displayName: "C++ (Clang)",
    standard: "C++23",
    extension: ".cpp",
    dockerImage: "judge-clang:latest",
    compiler: `Clang++ ${JUDGE_TOOLCHAIN_VERSIONS.clang}`,
    compileCommand: ["clang++", "-O2", "-std=c++23", "-o", "/workspace/solution", "/workspace/solution.cpp"],
    runCommand: ["/workspace/solution"],
  },
  scala: {
    language: "scala",
    displayName: "Scala",
    standard: "3.5",
    extension: ".scala",
    dockerImage: "judge-scala:latest",
    compiler: `Scala ${JUDGE_TOOLCHAIN_VERSIONS.scala}`,
    compileCommand: ["sh", "-c", "export HOME=/tmp && mkdir -p /workspace/out && scalac -d /workspace/out /workspace/solution.scala"],
    runCommand: ["sh", "-c", "export HOME=/tmp && scala -classpath /workspace/out Main"],
  },
  erlang: {
    language: "erlang",
    displayName: "Erlang",
    standard: "OTP 27",
    extension: ".erl",
    dockerImage: "judge-erlang:latest",
    compiler: `Erlang/OTP ${JUDGE_TOOLCHAIN_VERSIONS.erlang}`,
    compileCommand: ["sh", "-c", "HOME=/tmp erlc -o /workspace /workspace/solution.erl"],
    runCommand: ["sh", "-c", "HOME=/tmp erl -noshell -pa /workspace -s solution main -s init stop"],
  },
  commonlisp: {
    language: "commonlisp",
    displayName: "Common Lisp",
    standard: "SBCL",
    extension: ".lisp",
    dockerImage: "judge-commonlisp:latest",
    compiler: `SBCL ${JUDGE_TOOLCHAIN_VERSIONS.sbcl}`,
    compileCommand: null,
    runCommand: ["sbcl", "--script", "/workspace/solution.lisp"],
  },
  bash: {
    language: "bash",
    displayName: "Bash",
    standard: "5.2",
    extension: ".sh",
    dockerImage: "judge-bash:latest",
    compiler: `Bash ${JUDGE_TOOLCHAIN_VERSIONS.bash}`,
    compileCommand: null,
    runCommand: ["bash", "/workspace/solution.sh"],
  },
  befunge: {
    language: "befunge",
    displayName: "Befunge",
    standard: "Befunge-93",
    extension: ".bf",
    dockerImage: "judge-esoteric:latest",
    compiler: "Befunge Interpreter",
    compileCommand: null,
    runCommand: ["befunge93", "-q", "/workspace/solution.bf"],
  },
  aheui: {
    language: "aheui",
    displayName: "아희 (Aheui)",
    standard: null,
    extension: ".aheui",
    dockerImage: "judge-esoteric:latest",
    compiler: "Aheui Interpreter",
    compileCommand: null,
    runCommand: ["aheui", "/workspace/solution.aheui"],
  },
  hyeong: {
    language: "hyeong",
    displayName: "혀엉 (Hyeong)",
    standard: null,
    extension: ".hyeong",
    dockerImage: "judge-esoteric:latest",
    compiler: "Hyeong Interpreter",
    compileCommand: null,
    runCommand: ["hyeong", "run", "/workspace/solution.hyeong"],
  },
  whitespace: {
    language: "whitespace",
    displayName: "Whitespace",
    standard: null,
    extension: ".ws",
    dockerImage: "judge-esoteric:latest",
    compiler: "Whitespace Interpreter (Python)",
    compileCommand: null,
    runCommand: ["python3", "/usr/local/bin/whitespace.py", "/workspace/solution.ws"],
  },
  ada: {
    language: "ada",
    displayName: "Ada",
    standard: "Ada 2012",
    extension: ".adb",
    dockerImage: "judge-ada:latest",
    compiler: `GNAT (GCC ${JUDGE_TOOLCHAIN_VERSIONS.gnat})`,
    compileCommand: ["gnatmake", "-O2", "/workspace/solution.adb"],
    runCommand: ["/workspace/solution"],
  },
  clojure: {
    language: "clojure",
    displayName: "Clojure",
    standard: "1.12",
    extension: ".clj",
    dockerImage: "judge-clojure:latest",
    compiler: `Clojure ${JUDGE_TOOLCHAIN_VERSIONS.clojure} / Temurin ${JUDGE_TOOLCHAIN_VERSIONS.java}`,
    compileCommand: null,
    runCommand: ["sh", "-c", "java -cp '/usr/local/lib/clojure/*' clojure.main /workspace/solution.clj"],
  },
  prolog: {
    language: "prolog",
    displayName: "Prolog",
    standard: "SWI-Prolog",
    extension: ".pro",
    dockerImage: "judge-prolog:latest",
    compiler: `SWI-Prolog ${JUDGE_TOOLCHAIN_VERSIONS.swiprolog}`,
    compileCommand: null,
    runCommand: ["swipl", "-q", "-g", "main", "-t", "halt", "/workspace/solution.pro"],
  },
  tcl: {
    language: "tcl",
    displayName: "Tcl",
    standard: "8.6",
    extension: ".tcl",
    dockerImage: "judge-tcl:latest",
    compiler: `Tcl ${JUDGE_TOOLCHAIN_VERSIONS.tcl}`,
    compileCommand: null,
    runCommand: ["tclsh", "/workspace/solution.tcl"],
  },
  awk: {
    language: "awk",
    displayName: "AWK",
    standard: "gawk",
    extension: ".awk",
    dockerImage: "judge-awk:latest",
    compiler: `GNU AWK ${JUDGE_TOOLCHAIN_VERSIONS.gawk}`,
    compileCommand: null,
    runCommand: ["gawk", "-f", "/workspace/solution.awk"],
  },
  scheme: {
    language: "scheme",
    displayName: "Scheme",
    standard: "Chicken",
    extension: ".scm",
    dockerImage: "judge-scheme:latest",
    compiler: `Chicken Scheme ${JUDGE_TOOLCHAIN_VERSIONS.chicken}`,
    compileCommand: ["csc", "-O2", "-o", "/workspace/solution", "/workspace/solution.scm"],
    runCommand: ["/workspace/solution"],
  },
  groovy: {
    language: "groovy",
    displayName: "Groovy",
    standard: "4.0",
    extension: ".groovy",
    dockerImage: "judge-groovy:latest",
    compiler: `Groovy ${JUDGE_TOOLCHAIN_VERSIONS.groovy} / Temurin ${JUDGE_TOOLCHAIN_VERSIONS.java}`,
    compileCommand: null,
    runCommand: ["sh", "-c", "JAVA_OPTS='-Djava.io.tmpdir=/tmp -Duser.home=/tmp' groovy /workspace/solution.groovy"],
  },
  octave: {
    language: "octave",
    displayName: "Octave",
    standard: "9",
    extension: ".m",
    dockerImage: "judge-octave:latest",
    compiler: `GNU Octave ${JUDGE_TOOLCHAIN_VERSIONS.octave}`,
    compileCommand: null,
    runCommand: ["octave-cli", "--norc", "--quiet", "/workspace/solution.m"],
  },
  crystal: {
    language: "crystal",
    displayName: "Crystal",
    standard: "1.14",
    extension: ".cr",
    dockerImage: "judge-crystal:latest",
    compiler: `Crystal ${JUDGE_TOOLCHAIN_VERSIONS.crystal}`,
    compileCommand: ["crystal", "build", "--release", "-o", "/workspace/solution", "/workspace/solution.cr"],
    runCommand: ["/workspace/solution"],
  },
  powershell: {
    language: "powershell",
    displayName: "PowerShell",
    standard: "7.5",
    extension: ".ps1",
    dockerImage: "judge-powershell:latest",
    compiler: `PowerShell ${JUDGE_TOOLCHAIN_VERSIONS.powershell}`,
    compileCommand: null,
    runCommand: ["sh", "-c", "HOME=/tmp pwsh -NoProfile -NonInteractive -File /workspace/solution.ps1"],
  },
  postscript: {
    language: "postscript",
    displayName: "PostScript",
    standard: "Level 3",
    extension: ".ps",
    dockerImage: "judge-postscript:latest",
    compiler: `Ghostscript ${JUDGE_TOOLCHAIN_VERSIONS.ghostscript}`,
    compileCommand: null,
    runCommand: ["gs", "-q", "-dNODISPLAY", "-dBATCH", "-dNOPAUSE", "-dNOSAFER", "/workspace/solution.ps"],
  },
};

export const DEFAULT_JUDGE_LANGUAGES = Object.values(JUDGE_LANGUAGE_CONFIGS);

export function isJudgeLanguage(language: string): language is Language {
  return language in JUDGE_LANGUAGE_CONFIGS;
}

export function getJudgeLanguageDefinition(language: string) {
  return isJudgeLanguage(language) ? JUDGE_LANGUAGE_CONFIGS[language] : null;
}

export function serializeJudgeCommand(command: string[] | null | undefined) {
  return command?.join(" ") ?? null;
}
