import type { Language } from "@/types";

export const JUDGE_TOOLCHAIN_VERSIONS = {
  go: "1.26.1",
  java: "25.0.2",
  nodejs: "24.14.0",
  kotlin: "2.3.10",
  python: "3.14.3",
  pypy: "3.10",
  rust: "1.94.0",
  swift: "6.2.4",
  typescript: "6.0",
  mono: "6.12",
  r: "4.5",
  perl: "5.40",
  php: "8.4",
  ruby: "3.4",
  lua: "5.4",
  haskell: "9.4",
  dart: "3.8",
  zig: "0.13",
  nim: "2.2",
  ocaml: "4.14",
  elixir: "1.18",
  julia: "1.12",
  d: "1.39",
  racket: "8.10",
  vlang: "0.5",
  fortran: "14",
  fpc: "3.2",
  gnucobol: "3.2",
  clang: "18",
  scala: "3.5",
  erlang: "27",
  sbcl: "2.5",
  bash: "5.2",
  gnat: "14",
  clojure: "1.12",
  swiprolog: "9",
  tcl: "8.6",
  gawk: "5",
  chicken: "5",
  groovy: "4.0",
  octave: "9",
  crystal: "1.14",
  powershell: "7.5",
  ghostscript: "10",
  coffeescript: "2.7",
  nasm: "2.16",
  gforth: "0.7",
  a68g: "3.3",
  haxe: "4.3",
  rakudo: "2024.09",
  odin: "dev-2024-12",
  cbqn: "0.7",
  micropython: "1.24",
  janet: "1.40",
  c3c: "0.7",
  vala: "0.56",
  lean: "4.28",
  koka: "3.2",
  regina: "3.9",
  picat: "3.9",
  mercury: "22.01.8",
  wabt: "1.0.40",
  wasmtime: "43.0.0",
  purescript: "0.15.16",
  factor: "0.101",
  minizinc: "2.9.5",
  pakcs: "3.9.0",
  clean: "3.1",
  carp: "0.5.5",
  grain: "0.7.2",
  pony: "0.61.1",
  moonbit: "0.8",
  chapel: "2.8",
  idris2: "0.8.0",
  rescript: "12.2",
  elm: "0.19.1",
} as const;

export interface JudgeLanguageDefinition {
  language: Language;
  displayName: string;
  standard: string | null;
  extension: string;
  dockerImage: string;
  compiler: string | null;
  compileCommand: string[] | null;
  runCommand: string[];
}

/** Human-readable base OS / toolchain description for each Docker judge image. */
export const DOCKER_IMAGE_RUNTIME_INFO: Record<string, string> = {
  "judge-cpp:latest": `Alpine 3.21 / GCC ${JUDGE_TOOLCHAIN_VERSIONS.fortran}`,
  "judge-clang:latest": `Alpine 3.21 / Clang ${JUDGE_TOOLCHAIN_VERSIONS.clang}`,
  "judge-python:latest": `Alpine / CPython ${JUDGE_TOOLCHAIN_VERSIONS.python}`,
  "judge-pypy:latest": `Debian slim / PyPy ${JUDGE_TOOLCHAIN_VERSIONS.pypy}`,
  "judge-node:latest": `Alpine / Node.js ${JUDGE_TOOLCHAIN_VERSIONS.nodejs}`,
  "judge-jvm:latest": `Alpine / Temurin ${JUDGE_TOOLCHAIN_VERSIONS.java} + Kotlin ${JUDGE_TOOLCHAIN_VERSIONS.kotlin}`,
  "judge-rust:latest": `Debian Bookworm / Rust ${JUDGE_TOOLCHAIN_VERSIONS.rust}`,
  "judge-go:latest": `Alpine / Go ${JUDGE_TOOLCHAIN_VERSIONS.go}`,
  "judge-swift:latest": `Ubuntu Noble / Swift ${JUDGE_TOOLCHAIN_VERSIONS.swift}`,
  "judge-csharp:latest": `Mono ${JUDGE_TOOLCHAIN_VERSIONS.mono}`,
  "judge-r:latest": `R ${JUDGE_TOOLCHAIN_VERSIONS.r}`,
  "judge-perl:latest": `Alpine 3.21 / Perl ${JUDGE_TOOLCHAIN_VERSIONS.perl}`,
  "judge-php:latest": `Alpine / PHP ${JUDGE_TOOLCHAIN_VERSIONS.php}`,
  "judge-ruby:latest": `Alpine 3.21 / Ruby ${JUDGE_TOOLCHAIN_VERSIONS.ruby}`,
  "judge-lua:latest": `Alpine 3.21 / Lua ${JUDGE_TOOLCHAIN_VERSIONS.lua}`,
  "judge-haskell:latest": `Debian Bookworm / GHC ${JUDGE_TOOLCHAIN_VERSIONS.haskell}`,
  "judge-dart:latest": `Debian Bookworm / Dart ${JUDGE_TOOLCHAIN_VERSIONS.dart}`,
  "judge-zig:latest": `Alpine 3.21 / Zig ${JUDGE_TOOLCHAIN_VERSIONS.zig}`,
  "judge-nim:latest": `Alpine 3.21 / Nim ${JUDGE_TOOLCHAIN_VERSIONS.nim}`,
  "judge-ocaml:latest": `Alpine 3.21 / OCaml ${JUDGE_TOOLCHAIN_VERSIONS.ocaml}`,
  "judge-elixir:latest": `Debian Bookworm / Elixir ${JUDGE_TOOLCHAIN_VERSIONS.elixir}`,
  "judge-julia:latest": `Debian Bookworm / Julia ${JUDGE_TOOLCHAIN_VERSIONS.julia}`,
  "judge-d:latest": `Ubuntu Noble / LDC2 ${JUDGE_TOOLCHAIN_VERSIONS.d}`,
  "judge-racket:latest": `Debian Bookworm / Racket ${JUDGE_TOOLCHAIN_VERSIONS.racket}`,
  "judge-v:latest": `Alpine 3.21 / V ${JUDGE_TOOLCHAIN_VERSIONS.vlang}`,
  "judge-fortran:latest": `Alpine 3.21 / GFortran ${JUDGE_TOOLCHAIN_VERSIONS.fortran}`,
  "judge-pascal:latest": `Debian Bookworm / FPC ${JUDGE_TOOLCHAIN_VERSIONS.fpc}`,
  "judge-brainfuck:latest": "Debian Bookworm / beef interpreter",
  "judge-cobol:latest": `Debian Bookworm / GnuCOBOL ${JUDGE_TOOLCHAIN_VERSIONS.gnucobol}`,
  "judge-scala:latest": `Alpine / Scala ${JUDGE_TOOLCHAIN_VERSIONS.scala}`,
  "judge-erlang:latest": `Debian Bookworm / OTP ${JUDGE_TOOLCHAIN_VERSIONS.erlang}`,
  "judge-commonlisp:latest": `Debian Bookworm / SBCL ${JUDGE_TOOLCHAIN_VERSIONS.sbcl}`,
  "judge-bash:latest": `Debian Bookworm / Bash ${JUDGE_TOOLCHAIN_VERSIONS.bash}`,
  "judge-esoteric:latest": "Debian Bookworm / Befunge-93 + Aheui (PyPI) + Hyeong (Rust) + Whitespace (Python)",
  "judge-ada:latest": `Alpine 3.21 / GNAT (GCC ${JUDGE_TOOLCHAIN_VERSIONS.gnat})`,
  "judge-clojure:latest": `Alpine / Clojure ${JUDGE_TOOLCHAIN_VERSIONS.clojure} / Temurin ${JUDGE_TOOLCHAIN_VERSIONS.java}`,
  "judge-prolog:latest": `Debian Bookworm / SWI-Prolog ${JUDGE_TOOLCHAIN_VERSIONS.swiprolog}`,
  "judge-tcl:latest": `Alpine 3.21 / Tcl ${JUDGE_TOOLCHAIN_VERSIONS.tcl}`,
  "judge-awk:latest": `Alpine 3.21 / GNU AWK ${JUDGE_TOOLCHAIN_VERSIONS.gawk}`,
  "judge-scheme:latest": `Debian Bookworm / Chicken Scheme ${JUDGE_TOOLCHAIN_VERSIONS.chicken}`,
  "judge-groovy:latest": `Alpine / Groovy ${JUDGE_TOOLCHAIN_VERSIONS.groovy} / Temurin 21`,
  "judge-octave:latest": `Alpine 3.21 / GNU Octave ${JUDGE_TOOLCHAIN_VERSIONS.octave}`,
  "judge-crystal:latest": `Debian Bookworm / Crystal ${JUDGE_TOOLCHAIN_VERSIONS.crystal}`,
  "judge-powershell:latest": `Debian Bookworm / PowerShell ${JUDGE_TOOLCHAIN_VERSIONS.powershell}`,
  "judge-postscript:latest": `Alpine 3.21 / Ghostscript ${JUDGE_TOOLCHAIN_VERSIONS.ghostscript}`,
  "judge-fsharp:latest": "Alpine / .NET SDK 10.0 (compiled)",
  "judge-apl:latest": "Debian Bookworm / GNU APL 1.8",
  "judge-freebasic:latest": "Debian Bookworm / FreeBASIC 1.10.1",
  "judge-smalltalk:latest": "Ubuntu 22.04 / GNU Smalltalk",
  "judge-b:latest": "Debian Bookworm / BCause (amd64) or bext-lang B compiler (arm64)",
  "judge-nasm:latest": "Alpine 3.21 / NASM (x86-64) or GNU as (arm64)",
  "judge-bqn:latest": "Debian Bookworm / CBQN",
  "judge-lolcode:latest": "Debian Bookworm / lci (LOLCODE interpreter)",
  "judge-forth:latest": "Alpine 3.21 / Gforth",
  "judge-algol68:latest": "Debian Bookworm / Algol 68 Genie",
  "judge-umjunsik:latest": "Rust slim-bookworm / umjunsik",
  "judge-haxe:latest": `Debian Bookworm / Haxe ${JUDGE_TOOLCHAIN_VERSIONS.haxe} (Python backend)`,
  "judge-raku:latest": `Alpine / Rakudo Star ${JUDGE_TOOLCHAIN_VERSIONS.rakudo}`,

  "judge-shakespeare:latest": "Python 3.12 slim-bookworm / shakespearelang (pip)",
  "judge-snobol4:latest": "Debian Bookworm / CSNOBOL4",
  "judge-icon:latest": "Debian Bookworm / Icon (Unicon)",
  "judge-uiua:latest": "Rust slim-bookworm / Uiua",
  "judge-odin:latest": "Debian Bookworm / Odin + LLVM",
  "judge-objective-c:latest": "Debian Bookworm / GCC + gobjc",
  "judge-deno:latest": "Alpine / Deno",
  "judge-bun:latest": "Alpine / Bun",
  "judge-gleam:latest": "Erlang 27 Alpine / Gleam 1.7",
  "judge-sml:latest": "Debian Bookworm / Poly/ML",
  "judge-micropython:latest": `Alpine edge / MicroPython ${JUDGE_TOOLCHAIN_VERSIONS.micropython}`,
  "judge-squirrel:latest": "Debian Bookworm / Squirrel 3.2",
  "judge-rexx:latest": `Debian Bookworm / Regina REXX ${JUDGE_TOOLCHAIN_VERSIONS.regina}`,
  "judge-hy:latest": "Python 3.13 Alpine / Hy 1.0",
  "judge-arturo:latest": "Official arturolang/arturo",
  "judge-janet:latest": `Alpine 3.21 / Janet ${JUDGE_TOOLCHAIN_VERSIONS.janet}`,
  "judge-c3:latest": `Debian Bookworm / C3 ${JUDGE_TOOLCHAIN_VERSIONS.c3c}`,
  "judge-vala:latest": `Debian Bookworm / Vala ${JUDGE_TOOLCHAIN_VERSIONS.vala}`,
  "judge-nelua:latest": "Debian Bookworm / Nelua (git)",
  "judge-hare:latest": "Alpine 3.21 / Hare 0.24",
  "judge-koka:latest": `Ubuntu 22.04 / Koka ${JUDGE_TOOLCHAIN_VERSIONS.koka}`,
  "judge-lean:latest": `Ubuntu 24.04 / Lean 4 ${JUDGE_TOOLCHAIN_VERSIONS.lean}`,
  "judge-picat:latest": `Alpine 3.21 / Picat ${JUDGE_TOOLCHAIN_VERSIONS.picat}`,
  "judge-mercury:latest": `Debian Bookworm / Mercury ${JUDGE_TOOLCHAIN_VERSIONS.mercury}`,
  "judge-wat:latest": `Alpine 3.21 / wabt ${JUDGE_TOOLCHAIN_VERSIONS.wabt} + wasmtime ${JUDGE_TOOLCHAIN_VERSIONS.wasmtime}`,
  "judge-purescript:latest": `Debian Bookworm / PureScript ${JUDGE_TOOLCHAIN_VERSIONS.purescript} + Node.js`,
  "judge-modula2:latest": `Alpine 3.21 / GCC gm2 ${JUDGE_TOOLCHAIN_VERSIONS.fortran}`,
  "judge-factor:latest": `Debian Bookworm / Factor ${JUDGE_TOOLCHAIN_VERSIONS.factor}`,
  "judge-minizinc:latest": `Debian Bookworm / MiniZinc ${JUDGE_TOOLCHAIN_VERSIONS.minizinc}`,
  "judge-curry:latest": `Debian Bookworm / PAKCS ${JUDGE_TOOLCHAIN_VERSIONS.pakcs}`,
  "judge-clean:latest": `Debian Bookworm / Clean ${JUDGE_TOOLCHAIN_VERSIONS.clean}`,
  "judge-carp:latest": `Debian Bookworm / Carp ${JUDGE_TOOLCHAIN_VERSIONS.carp}`,
  "judge-grain:latest": `Debian Bookworm / Grain ${JUDGE_TOOLCHAIN_VERSIONS.grain}`,
  "judge-pony:latest": `Alpine 3.21 / Pony ${JUDGE_TOOLCHAIN_VERSIONS.pony}`,
  "judge-moonbit:latest": `Ubuntu 24.04 / MoonBit ${JUDGE_TOOLCHAIN_VERSIONS.moonbit} (native)`,
  "judge-chapel:latest": `Chapel ${JUDGE_TOOLCHAIN_VERSIONS.chapel} (official)`,
  "judge-idris2:latest": `Debian Bookworm / Idris 2 ${JUDGE_TOOLCHAIN_VERSIONS.idris2} + Chez Scheme`,
  "judge-rescript:latest": `Node.js 24 Alpine / ReScript ${JUDGE_TOOLCHAIN_VERSIONS.rescript}`,
  "judge-elm:latest": `Node.js 24 Alpine / Elm ${JUDGE_TOOLCHAIN_VERSIONS.elm}`,
};

export function getDockerImageRuntimeInfo(dockerImage: string): string {
  return DOCKER_IMAGE_RUNTIME_INFO[dockerImage] ?? dockerImage;
}

export const JUDGE_LANGUAGE_CONFIGS: Record<Language, JudgeLanguageDefinition> = {
  c17: {
    language: "c17",
    displayName: "C",
    standard: "C17",
    extension: ".c",
    dockerImage: "judge-cpp:latest",
    compiler: "GCC (gcc)",
    compileCommand: ["gcc", "-O2", "-std=c17", "-o", "/workspace/solution", "/workspace/solution.c", "-lm"],
    runCommand: ["/workspace/solution"],
  },
  c23: {
    language: "c23",
    displayName: "C",
    standard: "C23",
    extension: ".c",
    dockerImage: "judge-cpp:latest",
    compiler: "GCC (gcc)",
    compileCommand: ["gcc", "-O2", "-std=c23", "-o", "/workspace/solution", "/workspace/solution.c", "-lm"],
    runCommand: ["/workspace/solution"],
  },
  cpp20: {
    language: "cpp20",
    displayName: "C++",
    standard: "C++20",
    extension: ".cpp",
    dockerImage: "judge-cpp:latest",
    compiler: "GCC (g++)",
    compileCommand: ["g++", "-O2", "-std=c++20", "-o", "/workspace/solution", "/workspace/solution.cpp"],
    runCommand: ["/workspace/solution"],
  },
  cpp23: {
    language: "cpp23",
    displayName: "C++",
    standard: "C++23",
    extension: ".cpp",
    dockerImage: "judge-cpp:latest",
    compiler: "GCC (g++)",
    compileCommand: ["g++", "-O2", "-std=c++23", "-o", "/workspace/solution", "/workspace/solution.cpp"],
    runCommand: ["/workspace/solution"],
  },
  cpp26: {
    language: "cpp26",
    displayName: "C++",
    standard: "C++26",
    extension: ".cpp",
    dockerImage: "judge-cpp:latest",
    compiler: "GCC (g++)",
    compileCommand: ["g++", "-O2", "-std=c++26", "-o", "/workspace/solution", "/workspace/solution.cpp"],
    runCommand: ["/workspace/solution"],
  },
  java: {
    language: "java",
    displayName: "Java",
    standard: "25",
    extension: ".java",
    dockerImage: "judge-jvm:latest",
    compiler: `Eclipse Temurin ${JUDGE_TOOLCHAIN_VERSIONS.java} (javac/java)`,
    compileCommand: [
      "sh",
      "-c",
      "export JAVA_TOOL_OPTIONS='-Djava.io.tmpdir=/workspace' && mkdir -p /workspace/out && cp /workspace/solution.java /workspace/Main.java && javac --release 25 -encoding UTF-8 -d /workspace/out /workspace/Main.java",
    ],
    runCommand: ["java", "-Djava.io.tmpdir=/workspace", "-cp", "/workspace/out", "Main"],
  },
  python: {
    language: "python",
    displayName: "Python",
    standard: "3.14",
    extension: ".py",
    dockerImage: "judge-python:latest",
    compiler: `Python ${JUDGE_TOOLCHAIN_VERSIONS.python}`,
    compileCommand: null,
    runCommand: ["python3", "/workspace/solution.py"],
  },
  pypy: {
    language: "pypy",
    displayName: "PyPy",
    standard: JUDGE_TOOLCHAIN_VERSIONS.pypy,
    extension: ".py",
    dockerImage: "judge-pypy:latest",
    compiler: `PyPy ${JUDGE_TOOLCHAIN_VERSIONS.pypy}`,
    compileCommand: null,
    runCommand: ["pypy3", "/workspace/solution.py"],
  },
  javascript: {
    language: "javascript",
    displayName: "JavaScript",
    standard: "Node.js 24",
    extension: ".js",
    dockerImage: "judge-node:latest",
    compiler: `Node.js ${JUDGE_TOOLCHAIN_VERSIONS.nodejs} (LTS)`,
    compileCommand: null,
    runCommand: ["node", "/workspace/solution.js"],
  },
  typescript: {
    language: "typescript",
    displayName: "TypeScript",
    standard: "TS 5.9",
    extension: ".ts",
    dockerImage: "judge-node:latest",
    compiler: `TypeScript ${JUDGE_TOOLCHAIN_VERSIONS.typescript} (tsc) / Node.js ${JUDGE_TOOLCHAIN_VERSIONS.nodejs}`,
    compileCommand: [
      "tsc",
      "--pretty",
      "false",
      "--strict",
      "--skipLibCheck",
      "--types",
      "node",
      "--typeRoots",
      "/usr/local/lib/node_modules/@types",
      "--target",
      "ES2024",
      "--module",
      "commonjs",
      "--outDir",
      "/workspace/dist",
      "/workspace/solution.ts",
    ],
    runCommand: ["node", "/workspace/dist/solution.js"],
  },
  plaintext: {
    language: "plaintext",
    displayName: "Plaintext",
    standard: "Output-only",
    extension: ".txt",
    dockerImage: "judge-node:latest",
    compiler: `Output-only passthrough / Node.js ${JUDGE_TOOLCHAIN_VERSIONS.nodejs}`,
    compileCommand: null,
    runCommand: ["node", "/opt/judge-output/runner.mjs", "plaintext", "/workspace/solution.txt"],
  },
  verilog: {
    language: "verilog",
    displayName: "Verilog",
    standard: "Output-only",
    extension: ".v",
    dockerImage: "judge-node:latest",
    compiler: `Literal $display extractor / Node.js ${JUDGE_TOOLCHAIN_VERSIONS.nodejs}`,
    compileCommand: null,
    runCommand: ["node", "/opt/judge-output/runner.mjs", "verilog", "/workspace/solution.v"],
  },
  systemverilog: {
    language: "systemverilog",
    displayName: "SystemVerilog",
    standard: "Output-only",
    extension: ".sv",
    dockerImage: "judge-node:latest",
    compiler: `Literal $display extractor / Node.js ${JUDGE_TOOLCHAIN_VERSIONS.nodejs}`,
    compileCommand: null,
    runCommand: ["node", "/opt/judge-output/runner.mjs", "systemverilog", "/workspace/solution.sv"],
  },
  vhdl: {
    language: "vhdl",
    displayName: "VHDL",
    standard: "Output-only",
    extension: ".vhd",
    dockerImage: "judge-node:latest",
    compiler: `Literal report extractor / Node.js ${JUDGE_TOOLCHAIN_VERSIONS.nodejs}`,
    compileCommand: null,
    runCommand: ["node", "/opt/judge-output/runner.mjs", "vhdl", "/workspace/solution.vhd"],
  },
  kotlin: {
    language: "kotlin",
    displayName: "Kotlin",
    standard: "2.3",
    extension: ".kt",
    dockerImage: "judge-jvm:latest",
    compiler: `Kotlin ${JUDGE_TOOLCHAIN_VERSIONS.kotlin} / Eclipse Temurin ${JUDGE_TOOLCHAIN_VERSIONS.java}`,
    compileCommand: [
      "kotlinc",
      "-J-Djava.io.tmpdir=/workspace",
      "/workspace/solution.kt",
      "-include-runtime",
      "-d",
      "/workspace/solution.jar",
    ],
    runCommand: ["java", "-Djava.io.tmpdir=/workspace", "-jar", "/workspace/solution.jar"],
  },
  rust: {
    language: "rust",
    displayName: "Rust",
    standard: "1.94",
    extension: ".rs",
    dockerImage: "judge-rust:latest",
    compiler: `Rust ${JUDGE_TOOLCHAIN_VERSIONS.rust} (rustc)`,
    compileCommand: ["rustc", "-O", "-o", "/workspace/solution", "/workspace/solution.rs"],
    runCommand: ["/workspace/solution"],
  },
  go: {
    language: "go",
    displayName: "Go",
    standard: "1.26",
    extension: ".go",
    dockerImage: "judge-go:latest",
    compiler: `Go ${JUDGE_TOOLCHAIN_VERSIONS.go}`,
    compileCommand: ["go", "build", "-o", "/workspace/solution", "/workspace/solution.go"],
    runCommand: ["/workspace/solution"],
  },
  swift: {
    language: "swift",
    displayName: "Swift",
    standard: "6.2",
    extension: ".swift",
    dockerImage: "judge-swift:latest",
    compiler: `Swift ${JUDGE_TOOLCHAIN_VERSIONS.swift}`,
    compileCommand: [
      "swiftc",
      "-O",
      "-module-cache-path",
      "/tmp/swift-module-cache",
      "-o",
      "/workspace/solution",
      "/workspace/solution.swift",
    ],
    runCommand: ["/workspace/solution"],
  },
  csharp: {
    language: "csharp",
    displayName: "C#",
    standard: "Mono 6",
    extension: ".cs",
    dockerImage: "judge-csharp:latest",
    compiler: `Mono ${JUDGE_TOOLCHAIN_VERSIONS.mono} (mcs)`,
    compileCommand: ["sh", "-c", "HOME=/tmp mcs -optimize+ -out:/workspace/solution.exe /workspace/solution.cs"],
    runCommand: ["sh", "-c", "HOME=/tmp mono /workspace/solution.exe"],
  },
  r: {
    language: "r",
    displayName: "R",
    standard: "4.5",
    extension: ".r",
    dockerImage: "judge-r:latest",
    compiler: `R ${JUDGE_TOOLCHAIN_VERSIONS.r}`,
    compileCommand: null,
    runCommand: ["Rscript", "/workspace/solution.r"],
  },
  perl: {
    language: "perl",
    displayName: "Perl",
    standard: "5.40",
    extension: ".pl",
    dockerImage: "judge-perl:latest",
    compiler: `Perl ${JUDGE_TOOLCHAIN_VERSIONS.perl}`,
    compileCommand: null,
    runCommand: ["perl", "/workspace/solution.pl"],
  },
  php: {
    language: "php",
    displayName: "PHP",
    standard: "8.4",
    extension: ".php",
    dockerImage: "judge-php:latest",
    compiler: `PHP ${JUDGE_TOOLCHAIN_VERSIONS.php}`,
    compileCommand: null,
    runCommand: ["php", "/workspace/solution.php"],
  },
  ruby: {
    language: "ruby",
    displayName: "Ruby",
    standard: "3.4",
    extension: ".rb",
    dockerImage: "judge-ruby:latest",
    compiler: `Ruby ${JUDGE_TOOLCHAIN_VERSIONS.ruby}`,
    compileCommand: null,
    runCommand: ["ruby", "/workspace/solution.rb"],
  },
  lua: {
    language: "lua",
    displayName: "Lua",
    standard: "5.4",
    extension: ".lua",
    dockerImage: "judge-lua:latest",
    compiler: `Lua ${JUDGE_TOOLCHAIN_VERSIONS.lua}`,
    compileCommand: null,
    runCommand: ["lua5.4", "/workspace/solution.lua"],
  },
  haskell: {
    language: "haskell",
    displayName: "Haskell",
    standard: "GHC 9.4",
    extension: ".hs",
    dockerImage: "judge-haskell:latest",
    compiler: `GHC ${JUDGE_TOOLCHAIN_VERSIONS.haskell}`,
    compileCommand: ["ghc", "-O2", "-o", "/workspace/solution", "/workspace/solution.hs"],
    runCommand: ["/workspace/solution"],
  },
  dart: {
    language: "dart",
    displayName: "Dart",
    standard: "3.8",
    extension: ".dart",
    dockerImage: "judge-dart:latest",
    compiler: `Dart ${JUDGE_TOOLCHAIN_VERSIONS.dart}`,
    compileCommand: ["sh", "-c", "HOME=/tmp dart compile exe --suppress-analytics /workspace/solution.dart -o /workspace/solution"],
    runCommand: ["/workspace/solution"],
  },
  zig: {
    language: "zig",
    displayName: "Zig",
    standard: "0.13",
    extension: ".zig",
    dockerImage: "judge-zig:latest",
    compiler: `Zig ${JUDGE_TOOLCHAIN_VERSIONS.zig}`,
    compileCommand: ["sh", "-c", "zig build-exe --cache-dir /tmp/zig-cache --global-cache-dir /tmp/zig-global -femit-bin=/workspace/solution /workspace/solution.zig -O ReleaseSafe"],
    runCommand: ["/workspace/solution"],
  },
  nim: {
    language: "nim",
    displayName: "Nim",
    standard: "2.2",
    extension: ".nim",
    dockerImage: "judge-nim:latest",
    compiler: `Nim ${JUDGE_TOOLCHAIN_VERSIONS.nim}`,
    compileCommand: ["sh", "-c", "mkdir -p /tmp/nimcache && nim compile --opt:speed -d:release --nimcache:/tmp/nimcache --out:/workspace/solution /workspace/solution.nim"],
    runCommand: ["/workspace/solution"],
  },
  ocaml: {
    language: "ocaml",
    displayName: "OCaml",
    standard: "4.14",
    extension: ".ml",
    dockerImage: "judge-ocaml:latest",
    compiler: `OCaml ${JUDGE_TOOLCHAIN_VERSIONS.ocaml}`,
    compileCommand: ["ocamlfind", "ocamlopt", "-package", "str", "-linkpkg", "-O2", "-o", "/workspace/solution", "/workspace/solution.ml"],
    runCommand: ["/workspace/solution"],
  },
  elixir: {
    language: "elixir",
    displayName: "Elixir",
    standard: "1.18",
    extension: ".exs",
    dockerImage: "judge-elixir:latest",
    compiler: `Elixir ${JUDGE_TOOLCHAIN_VERSIONS.elixir}`,
    compileCommand: null,
    runCommand: ["sh", "-c", "HOME=/tmp elixir /workspace/solution.exs"],
  },
  julia: {
    language: "julia",
    displayName: "Julia",
    standard: "1.12",
    extension: ".jl",
    dockerImage: "judge-julia:latest",
    compiler: `Julia ${JUDGE_TOOLCHAIN_VERSIONS.julia}`,
    compileCommand: null,
    runCommand: ["julia", "/workspace/solution.jl"],
  },
  d: {
    language: "d",
    displayName: "D",
    standard: "LDC2",
    extension: ".d",
    dockerImage: "judge-d:latest",
    compiler: `LDC2 ${JUDGE_TOOLCHAIN_VERSIONS.d}`,
    compileCommand: ["ldc2", "-O2", "-of=/workspace/solution", "/workspace/solution.d"],
    runCommand: ["/workspace/solution"],
  },
  racket: {
    language: "racket",
    displayName: "Racket",
    standard: "8.10",
    extension: ".rkt",
    dockerImage: "judge-racket:latest",
    compiler: `Racket ${JUDGE_TOOLCHAIN_VERSIONS.racket}`,
    compileCommand: null,
    runCommand: ["racket", "/workspace/solution.rkt"],
  },
  vlang: {
    language: "vlang",
    displayName: "V",
    standard: "0.5",
    extension: ".v",
    dockerImage: "judge-v:latest",
    compiler: `V ${JUDGE_TOOLCHAIN_VERSIONS.vlang}`,
    compileCommand: ["sh", "-c", "HOME=/tmp v -prod -o /workspace/solution /workspace/solution.v"],
    runCommand: ["/workspace/solution"],
  },
  c99: {
    language: "c99",
    displayName: "C",
    standard: "C99",
    extension: ".c",
    dockerImage: "judge-cpp:latest",
    compiler: "GCC (gcc)",
    compileCommand: ["gcc", "-O2", "-std=c99", "-o", "/workspace/solution", "/workspace/solution.c", "-lm"],
    runCommand: ["/workspace/solution"],
  },
  c89: {
    language: "c89",
    displayName: "C",
    standard: "ANSI C (C89)",
    extension: ".c",
    dockerImage: "judge-cpp:latest",
    compiler: "GCC (gcc)",
    compileCommand: ["gcc", "-O2", "-std=c89", "-o", "/workspace/solution", "/workspace/solution.c", "-lm"],
    runCommand: ["/workspace/solution"],
  },
  fortran: {
    language: "fortran",
    displayName: "Fortran",
    standard: "Fortran 2018",
    extension: ".f90",
    dockerImage: "judge-fortran:latest",
    compiler: `GFortran ${JUDGE_TOOLCHAIN_VERSIONS.fortran}`,
    compileCommand: ["gfortran", "-O2", "-std=f2018", "-o", "/workspace/solution", "/workspace/solution.f90"],
    runCommand: ["/workspace/solution"],
  },
  pascal: {
    language: "pascal",
    displayName: "Pascal",
    standard: "Free Pascal 3.2",
    extension: ".pas",
    dockerImage: "judge-pascal:latest",
    compiler: `Free Pascal ${JUDGE_TOOLCHAIN_VERSIONS.fpc}`,
    compileCommand: ["fpc", "-O2", "-o/workspace/solution", "/workspace/solution.pas"],
    runCommand: ["/workspace/solution"],
  },
  brainfuck: {
    language: "brainfuck",
    displayName: "Brainfuck",
    standard: null,
    extension: ".bf",
    dockerImage: "judge-brainfuck:latest",
    compiler: "bf interpreter",
    compileCommand: null,
    runCommand: ["beef", "/workspace/solution.bf"],
  },
  cobol: {
    language: "cobol",
    displayName: "COBOL",
    standard: "GnuCOBOL 3.2",
    extension: ".cob",
    dockerImage: "judge-cobol:latest",
    compiler: `GnuCOBOL ${JUDGE_TOOLCHAIN_VERSIONS.gnucobol}`,
    compileCommand: ["cobc", "-x", "-O2", "-o", "/workspace/solution", "/workspace/solution.cob"],
    runCommand: ["/workspace/solution"],
  },
  clang_c23: {
    language: "clang_c23",
    displayName: "C (Clang)",
    standard: "C23",
    extension: ".c",
    dockerImage: "judge-clang:latest",
    compiler: `Clang ${JUDGE_TOOLCHAIN_VERSIONS.clang}`,
    compileCommand: ["clang", "-O2", "-std=c23", "-o", "/workspace/solution", "/workspace/solution.c", "-lm"],
    runCommand: ["/workspace/solution"],
  },
  clang_cpp23: {
    language: "clang_cpp23",
    displayName: "C++ (Clang)",
    standard: "C++23",
    extension: ".cpp",
    dockerImage: "judge-clang:latest",
    compiler: `Clang++ ${JUDGE_TOOLCHAIN_VERSIONS.clang}`,
    compileCommand: ["clang++", "-O2", "-std=c++23", "-o", "/workspace/solution", "/workspace/solution.cpp"],
    runCommand: ["/workspace/solution"],
  },
  clang_cpp26: {
    language: "clang_cpp26",
    displayName: "C++ (Clang)",
    standard: "C++26",
    extension: ".cpp",
    dockerImage: "judge-clang:latest",
    compiler: `Clang++ ${JUDGE_TOOLCHAIN_VERSIONS.clang}`,
    compileCommand: ["clang++", "-O2", "-std=c++26", "-o", "/workspace/solution", "/workspace/solution.cpp"],
    runCommand: ["/workspace/solution"],
  },
  scala: {
    language: "scala",
    displayName: "Scala",
    standard: "3.5",
    extension: ".scala",
    dockerImage: "judge-scala:latest",
    compiler: `Scala ${JUDGE_TOOLCHAIN_VERSIONS.scala}`,
    compileCommand: ["sh", "-c", "export HOME=/tmp && mkdir -p /workspace/out && /usr/local/bin/scalac -d /workspace/out /workspace/solution.scala"],
    runCommand: ["sh", "-c", "export HOME=/tmp && java -classpath \"/workspace/out:/opt/scala3/lib/*\" Main"],
  },
  erlang: {
    language: "erlang",
    displayName: "Erlang",
    standard: "OTP 27",
    extension: ".erl",
    dockerImage: "judge-erlang:latest",
    compiler: `Erlang/OTP ${JUDGE_TOOLCHAIN_VERSIONS.erlang}`,
    compileCommand: ["sh", "-c", "HOME=/tmp erlc -o /workspace /workspace/solution.erl"],
    runCommand: ["sh", "-c", "HOME=/tmp erl -noshell -pa /workspace -s solution main -s init stop"],
  },
  commonlisp: {
    language: "commonlisp",
    displayName: "Common Lisp",
    standard: "SBCL",
    extension: ".lisp",
    dockerImage: "judge-commonlisp:latest",
    compiler: `SBCL ${JUDGE_TOOLCHAIN_VERSIONS.sbcl}`,
    compileCommand: null,
    runCommand: ["sbcl", "--script", "/workspace/solution.lisp"],
  },
  bash: {
    language: "bash",
    displayName: "Bash",
    standard: "5.2",
    extension: ".sh",
    dockerImage: "judge-bash:latest",
    compiler: `Bash ${JUDGE_TOOLCHAIN_VERSIONS.bash}`,
    compileCommand: null,
    runCommand: ["bash", "/workspace/solution.sh"],
  },
  befunge: {
    language: "befunge",
    displayName: "Befunge",
    standard: "Befunge-93",
    extension: ".bf",
    dockerImage: "judge-esoteric:latest",
    compiler: "Befunge Interpreter",
    compileCommand: null,
    runCommand: ["befunge93", "-q", "/workspace/solution.bf"],
  },
  aheui: {
    language: "aheui",
    displayName: "아희 (Aheui)",
    standard: null,
    extension: ".aheui",
    dockerImage: "judge-esoteric:latest",
    compiler: "Aheui Interpreter",
    compileCommand: null,
    runCommand: ["aheui", "/workspace/solution.aheui"],
  },
  hyeong: {
    language: "hyeong",
    displayName: "혀엉 (Hyeong)",
    standard: null,
    extension: ".hyeong",
    dockerImage: "judge-esoteric:latest",
    compiler: "Hyeong Interpreter",
    compileCommand: null,
    runCommand: ["sh", "-c", "hyeong run --color never /workspace/solution.hyeong 2>&1 | grep -v '^==>'"],
  },
  whitespace: {
    language: "whitespace",
    displayName: "Whitespace",
    standard: null,
    extension: ".ws",
    dockerImage: "judge-esoteric:latest",
    compiler: "Whitespace Interpreter (Python)",
    compileCommand: null,
    runCommand: ["python3", "/usr/local/bin/whitespace.py", "/workspace/solution.ws"],
  },
  ada: {
    language: "ada",
    displayName: "Ada",
    standard: "Ada 2012",
    extension: ".adb",
    dockerImage: "judge-ada:latest",
    compiler: `GNAT (GCC ${JUDGE_TOOLCHAIN_VERSIONS.gnat})`,
    compileCommand: ["gnatmake", "-O2", "/workspace/solution.adb"],
    runCommand: ["/workspace/solution"],
  },
  clojure: {
    language: "clojure",
    displayName: "Clojure",
    standard: "1.12",
    extension: ".clj",
    dockerImage: "judge-clojure:latest",
    compiler: `Clojure ${JUDGE_TOOLCHAIN_VERSIONS.clojure} / Temurin ${JUDGE_TOOLCHAIN_VERSIONS.java}`,
    compileCommand: null,
    runCommand: ["sh", "-c", "java -cp '/usr/local/lib/clojure/*' clojure.main /workspace/solution.clj"],
  },
  prolog: {
    language: "prolog",
    displayName: "Prolog",
    standard: "SWI-Prolog",
    extension: ".pro",
    dockerImage: "judge-prolog:latest",
    compiler: `SWI-Prolog ${JUDGE_TOOLCHAIN_VERSIONS.swiprolog}`,
    compileCommand: null,
    runCommand: ["swipl", "-q", "-g", "main,halt(0)", "-t", "halt(0)", "/workspace/solution.pro"],
  },
  tcl: {
    language: "tcl",
    displayName: "Tcl",
    standard: "8.6",
    extension: ".tcl",
    dockerImage: "judge-tcl:latest",
    compiler: `Tcl ${JUDGE_TOOLCHAIN_VERSIONS.tcl}`,
    compileCommand: null,
    runCommand: ["tclsh", "/workspace/solution.tcl"],
  },
  awk: {
    language: "awk",
    displayName: "AWK",
    standard: "gawk",
    extension: ".awk",
    dockerImage: "judge-awk:latest",
    compiler: `GNU AWK ${JUDGE_TOOLCHAIN_VERSIONS.gawk}`,
    compileCommand: null,
    runCommand: ["gawk", "-f", "/workspace/solution.awk"],
  },
  scheme: {
    language: "scheme",
    displayName: "Scheme",
    standard: "Chicken",
    extension: ".scm",
    dockerImage: "judge-scheme:latest",
    compiler: `Chicken Scheme ${JUDGE_TOOLCHAIN_VERSIONS.chicken}`,
    compileCommand: ["csc", "-O2", "-o", "/workspace/solution", "/workspace/solution.scm"],
    runCommand: ["/workspace/solution"],
  },
  groovy: {
    language: "groovy",
    displayName: "Groovy",
    standard: "4.0",
    extension: ".groovy",
    dockerImage: "judge-groovy:latest",
    compiler: `Groovy ${JUDGE_TOOLCHAIN_VERSIONS.groovy} / Temurin 21`,
    compileCommand: ["sh", "-c", "groovyc -d /workspace /workspace/solution.groovy 2>&1"],
    runCommand: ["sh", "-c", "java -cp \"/workspace:/opt/groovy-4.0.24/lib/*\" solution"],
  },
  octave: {
    language: "octave",
    displayName: "Octave",
    standard: "9",
    extension: ".m",
    dockerImage: "judge-octave:latest",
    compiler: `GNU Octave ${JUDGE_TOOLCHAIN_VERSIONS.octave}`,
    compileCommand: null,
    runCommand: ["octave-cli", "--norc", "--quiet", "/workspace/solution.m"],
  },
  crystal: {
    language: "crystal",
    displayName: "Crystal",
    standard: "1.14",
    extension: ".cr",
    dockerImage: "judge-crystal:latest",
    compiler: `Crystal ${JUDGE_TOOLCHAIN_VERSIONS.crystal}`,
    compileCommand: ["crystal", "build", "--release", "-o", "/workspace/solution", "/workspace/solution.cr"],
    runCommand: ["/workspace/solution"],
  },
  powershell: {
    language: "powershell",
    displayName: "PowerShell",
    standard: "7.5",
    extension: ".ps1",
    dockerImage: "judge-powershell:latest",
    compiler: `PowerShell ${JUDGE_TOOLCHAIN_VERSIONS.powershell}`,
    compileCommand: null,
    runCommand: ["sh", "-c", "HOME=/tmp pwsh -NoProfile -NonInteractive -File /workspace/solution.ps1"],
  },
  postscript: {
    language: "postscript",
    displayName: "PostScript",
    standard: "Level 3",
    extension: ".ps",
    dockerImage: "judge-postscript:latest",
    compiler: `Ghostscript ${JUDGE_TOOLCHAIN_VERSIONS.ghostscript}`,
    compileCommand: null,
    runCommand: ["gs", "-q", "-dNODISPLAY", "-dBATCH", "-dNOPAUSE", "-dNOSAFER", "/workspace/solution.ps"],
  },
  delphi: {
    language: "delphi",
    displayName: "Delphi",
    standard: "Free Pascal (Delphi mode)",
    extension: ".dpr",
    dockerImage: "judge-pascal:latest",
    compiler: `Free Pascal ${JUDGE_TOOLCHAIN_VERSIONS.fpc} (Delphi mode)`,
    compileCommand: ["fpc", "-Mdelphi", "-O2", "-o/workspace/solution", "/workspace/solution.dpr"],
    runCommand: ["/workspace/solution"],
  },
  fsharp: {
    language: "fsharp",
    displayName: "F#",
    standard: ".NET 10",
    extension: ".fsx",
    dockerImage: "judge-fsharp:latest",
    compiler: "dotnet fsi (.NET)",
    compileCommand: ["sh", "-c", "mkdir -p /tmp/.nuget /tmp/.dotnet && echo ok"],
    runCommand: ["sh", "-c", "mkdir -p /tmp/.nuget /tmp/.dotnet && HOME=/tmp DOTNET_CLI_HOME=/tmp DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1 DOTNET_SKIP_WORKLOAD_INTEGRITY_CHECK=true DOTNET_NOLOGO=1 dotnet fsi /workspace/solution.fsx"],
  },
  apl: {
    language: "apl",
    displayName: "APL",
    standard: null,
    extension: ".apl",
    dockerImage: "judge-apl:latest",
    compiler: null,
    compileCommand: null,
    runCommand: ["sh", "-c", "apl --script -f /workspace/solution.apl 2>/dev/null"],
  },
  freebasic: {
    language: "freebasic",
    displayName: "FreeBASIC",
    standard: null,
    extension: ".bas",
    dockerImage: "judge-freebasic:latest",
    compiler: "fbc",
    compileCommand: ["sh", "-c", "cp /workspace/solution.bas /tmp/sol.bas && fbc -O 2 /tmp/sol.bas && cp /tmp/sol /workspace/solution"],
    runCommand: ["/workspace/solution"],
  },
  smalltalk: {
    language: "smalltalk",
    displayName: "Smalltalk",
    standard: null,
    extension: ".st",
    dockerImage: "judge-smalltalk:latest",
    compiler: null,
    compileCommand: null,
    runCommand: ["gst", "/workspace/solution.st"],
  },
  b: {
    language: "b",
    displayName: "B",
    standard: "BCause",
    extension: ".b",
    dockerImage: "judge-b:latest",
    compiler: "BCause B compiler",
    compileCommand: ["bcause", "-o", "/workspace/solution", "/workspace/solution.b"],
    runCommand: ["/workspace/solution"],
  },
  sed: {
    language: "sed",
    displayName: "Sed",
    standard: null,
    extension: ".sed",
    dockerImage: "judge-bash:latest",
    compiler: null,
    compileCommand: null,
    runCommand: ["sed", "-f", "/workspace/solution.sed"],
  },
  dc: {
    language: "dc",
    displayName: "dc",
    standard: null,
    extension: ".dc",
    dockerImage: "judge-bash:latest",
    compiler: null,
    compileCommand: null,
    runCommand: ["dc", "/workspace/solution.dc"],
  },
  coffeescript: {
    language: "coffeescript",
    displayName: "CoffeeScript",
    standard: `${JUDGE_TOOLCHAIN_VERSIONS.coffeescript}`,
    extension: ".coffee",
    dockerImage: "judge-node:latest",
    compiler: `CoffeeScript ${JUDGE_TOOLCHAIN_VERSIONS.coffeescript}`,
    compileCommand: null,
    runCommand: ["coffee", "/workspace/solution.coffee"],
  },
  llvm_ir: {
    language: "llvm_ir",
    displayName: "LLVM IR",
    standard: null,
    extension: ".ll",
    dockerImage: "judge-clang:latest",
    compiler: null,
    compileCommand: null,
    runCommand: ["lli", "/workspace/solution.ll"],
  },
  vbnet: {
    language: "vbnet",
    displayName: "Visual Basic .NET",
    standard: ".NET 10",
    extension: ".vb",
    dockerImage: "judge-fsharp:latest",
    compiler: "dotnet build (.NET)",
    compileCommand: [
      "sh", "-c",
      "mkdir -p /workspace/.nuget/packages /workspace/.dotnet /workspace/out /workspace/bin && echo '<Project Sdk=\"Microsoft.NET.Sdk\"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework><RootNamespace>Solution</RootNamespace></PropertyGroup></Project>' > /workspace/out/solution.vbproj && cp /workspace/solution.vb /workspace/out/Program.vb && cd /workspace/out && HOME=/workspace DOTNET_CLI_HOME=/workspace/.dotnet NUGET_PACKAGES=/workspace/.nuget/packages DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1 DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1 DOTNET_SKIP_WORKLOAD_INTEGRITY_CHECK=true DOTNET_NOLOGO=1 dotnet build -c Release -o /workspace/bin --nologo -v q -maxcpucount:1 -nodeReuse:false 2>&1",
    ],
    runCommand: ["/workspace/bin/solution"],
  },
  nasm: {
    language: "nasm",
    displayName: "Assembly",
    standard: "x86-64 / arm64",
    extension: ".asm",
    dockerImage: "judge-nasm:latest",
    compiler: "NASM (x86-64) / GNU as (arm64)",
    compileCommand: ["asm-compile"],
    runCommand: ["/workspace/solution"],
  },
  bqn: {
    language: "bqn",
    displayName: "BQN",
    standard: null,
    extension: ".bqn",
    dockerImage: "judge-bqn:latest",
    compiler: null,
    compileCommand: null,
    runCommand: ["bqn", "/workspace/solution.bqn"],
  },
  lolcode: {
    language: "lolcode",
    displayName: "LOLCODE",
    standard: null,
    extension: ".lol",
    dockerImage: "judge-lolcode:latest",
    compiler: null,
    compileCommand: null,
    runCommand: ["sh", "-c", "tr ' ' '\\n' | lci /workspace/solution.lol"],
  },
  forth: {
    language: "forth",
    displayName: "Forth",
    standard: null,
    extension: ".fth",
    dockerImage: "judge-forth:latest",
    compiler: null,
    compileCommand: null,
    runCommand: ["gforth", "/workspace/solution.fth", "-e", "bye"],
  },
  algol68: {
    language: "algol68",
    displayName: "Algol 68",
    standard: null,
    extension: ".a68",
    dockerImage: "judge-algol68:latest",
    compiler: null,
    compileCommand: null,
    runCommand: ["a68g", "/workspace/solution.a68"],
  },
  umjunsik: {
    language: "umjunsik",
    displayName: "엄준식 (Umjunsik)",
    standard: null,
    extension: ".umm",
    dockerImage: "judge-umjunsik:latest",
    compiler: null,
    compileCommand: null,
    runCommand: ["sh", "-c", "tr ' ' '\\n' | umjunsik /workspace/solution.umm"],
  },
  haxe: {
    language: "haxe",
    displayName: "Haxe",
    standard: `${JUDGE_TOOLCHAIN_VERSIONS.haxe}`,
    extension: ".hx",
    dockerImage: "judge-haxe:latest",
    compiler: `Haxe ${JUDGE_TOOLCHAIN_VERSIONS.haxe} (Python backend)`,
    compileCommand: [
      "sh",
      "-c",
      "HOME=/tmp && cp /workspace/solution.hx /workspace/Solution.hx && cd /workspace && haxe --main Solution --python /workspace/solution_out.py 2>&1",
    ],
    runCommand: ["python3", "/workspace/solution_out.py"],
  },
  raku: {
    language: "raku",
    displayName: "Raku",
    standard: `Rakudo ${JUDGE_TOOLCHAIN_VERSIONS.rakudo}`,
    extension: ".raku",
    dockerImage: "judge-raku:latest",
    compiler: `Rakudo ${JUDGE_TOOLCHAIN_VERSIONS.rakudo}`,
    compileCommand: null,
    runCommand: ["raku", "/workspace/solution.raku"],
  },

  shakespeare: {
    language: "shakespeare",
    displayName: "Shakespeare",
    standard: null,
    extension: ".spl",
    dockerImage: "judge-shakespeare:latest",
    compiler: null,
    compileCommand: null,
    runCommand: ["shakespeare_run", "/workspace/solution.spl"],
  },
  snobol4: {
    language: "snobol4",
    displayName: "SNOBOL4",
    standard: null,
    extension: ".sno",
    dockerImage: "judge-snobol4:latest",
    compiler: null,
    compileCommand: null,
    runCommand: ["snobol4", "/workspace/solution.sno"],
  },
  icon: {
    language: "icon",
    displayName: "Icon",
    standard: null,
    extension: ".icn",
    dockerImage: "judge-icon:latest",
    compiler: "icont",
    compileCommand: ["sh", "-c", "cd /workspace && icont -o /workspace/solution /workspace/solution.icn"],
    runCommand: ["/workspace/solution"],
  },
  uiua: {
    language: "uiua",
    displayName: "Uiua",
    standard: null,
    extension: ".ua",
    dockerImage: "judge-uiua:latest",
    compiler: null,
    compileCommand: null,
    runCommand: ["uiua", "run", "--no-format", "/workspace/solution.ua"],
  },
  odin: {
    language: "odin",
    displayName: "Odin",
    standard: null,
    extension: ".odin",
    dockerImage: "judge-odin:latest",
    compiler: "Odin",
    compileCommand: [
      "sh",
      "-c",
      "odin build /workspace/solution.odin -file -o:speed -out:/workspace/solution",
    ],
    runCommand: ["/workspace/solution"],
  },
  objective_c: {
    language: "objective_c",
    displayName: "Objective-C",
    standard: null,
    extension: ".m",
    dockerImage: "judge-objective-c:latest",
    compiler: "GCC (gobjc)",
    compileCommand: ["gcc", "-O2", "-lobjc", "-o", "/workspace/solution", "/workspace/solution.m"],
    runCommand: ["/workspace/solution"],
  },
  deno_js: {
    language: "deno_js",
    displayName: "JavaScript (Deno)",
    standard: null,
    extension: ".js",
    dockerImage: "judge-deno:latest",
    compiler: null,
    compileCommand: null,
    runCommand: ["deno", "run", "--allow-read", "/workspace/solution.js"],
  },
  deno_ts: {
    language: "deno_ts",
    displayName: "TypeScript (Deno)",
    standard: null,
    extension: ".ts",
    dockerImage: "judge-deno:latest",
    compiler: null,
    compileCommand: null,
    runCommand: ["deno", "run", "--allow-read", "/workspace/solution.ts"],
  },
  bun_js: {
    language: "bun_js",
    displayName: "JavaScript (Bun)",
    standard: null,
    extension: ".js",
    dockerImage: "judge-bun:latest",
    compiler: null,
    compileCommand: null,
    runCommand: ["bun", "run", "/workspace/solution.js"],
  },
  bun_ts: {
    language: "bun_ts",
    displayName: "TypeScript (Bun)",
    standard: null,
    extension: ".ts",
    dockerImage: "judge-bun:latest",
    compiler: null,
    compileCommand: null,
    runCommand: ["bun", "run", "/workspace/solution.ts"],
  },
  gleam: {
    language: "gleam",
    displayName: "Gleam",
    standard: null,
    extension: ".gleam",
    dockerImage: "judge-gleam:latest",
    compiler: "Gleam (Erlang target)",
    compileCommand: [
      "sh",
      "-c",
      "cp -r /opt/gleam-template /workspace/gleam-project && cp /workspace/solution.gleam /workspace/gleam-project/src/solution.gleam && rm -rf /workspace/gleam-project/test && cd /workspace/gleam-project && gleam build --target erlang 2>&1",
    ],
    runCommand: ["sh", "-c", "cd /workspace/gleam-project && erl -pa build/dev/erlang/*/ebin -noshell -eval \"'solution@@main':run(solution).\""],
  },
  sml: {
    language: "sml",
    displayName: "Standard ML",
    standard: null,
    extension: ".sml",
    dockerImage: "judge-sml:latest",
    compiler: "Poly/ML",
    compileCommand: ["sh", "-c", "polyc -o /workspace/solution /workspace/solution.sml"],
    runCommand: ["/workspace/solution"],
  },
  fennel: {
    language: "fennel",
    displayName: "Fennel",
    standard: null,
    extension: ".fnl",
    dockerImage: "judge-lua:latest",
    compiler: null,
    compileCommand: null,
    runCommand: ["fennel", "/workspace/solution.fnl"],
  },
  flix: {
    language: "flix",
    displayName: "Flix",
    standard: null,
    extension: ".flix",
    dockerImage: "judge-flix:latest",
    compiler: "Flix (JVM)",
    compileCommand: null,
    runCommand: ["sh", "-c", "cat > /tmp/in && cp -r /opt/flix-template/* /tmp/ && cp /workspace/solution.flix /tmp/src/Main.flix && cd /tmp && HOME=/tmp COURSIER_CACHE=/tmp/.cache java -Xmx400m -Djava.io.tmpdir=/tmp -jar /opt/flix.jar run"],
  },
  micropython: {
    language: "micropython",
    displayName: "MicroPython",
    standard: null,
    extension: ".py",
    dockerImage: "judge-micropython:latest",
    compiler: null,
    compileCommand: null,
    runCommand: ["micropython", "/workspace/solution.py"],
  },
  squirrel: {
    language: "squirrel",
    displayName: "Squirrel",
    standard: "3.2",
    extension: ".nut",
    dockerImage: "judge-squirrel:latest",
    compiler: null,
    compileCommand: null,
    runCommand: ["sq", "/workspace/solution.nut"],
  },
  rexx: {
    language: "rexx",
    displayName: "Rexx",
    standard: `Regina ${JUDGE_TOOLCHAIN_VERSIONS.regina}`,
    extension: ".rexx",
    dockerImage: "judge-rexx:latest",
    compiler: null,
    compileCommand: null,
    runCommand: ["regina", "/workspace/solution.rexx"],
  },
  hy: {
    language: "hy",
    displayName: "Hy",
    standard: "1.0",
    extension: ".hy",
    dockerImage: "judge-hy:latest",
    compiler: null,
    compileCommand: null,
    runCommand: ["hy", "/workspace/solution.hy"],
  },
  arturo: {
    language: "arturo",
    displayName: "Arturo",
    standard: null,
    extension: ".art",
    dockerImage: "judge-arturo:latest",
    compiler: null,
    compileCommand: null,
    runCommand: ["sh", "-c", "HOME=/tmp arturo /workspace/solution.art"],
  },
  janet: {
    language: "janet",
    displayName: "Janet",
    standard: `${JUDGE_TOOLCHAIN_VERSIONS.janet}`,
    extension: ".janet",
    dockerImage: "judge-janet:latest",
    compiler: null,
    compileCommand: null,
    runCommand: ["janet", "/workspace/solution.janet"],
  },
  c3: {
    language: "c3",
    displayName: "C3",
    standard: `${JUDGE_TOOLCHAIN_VERSIONS.c3c}`,
    extension: ".c3",
    dockerImage: "judge-c3:latest",
    compiler: `C3C ${JUDGE_TOOLCHAIN_VERSIONS.c3c}`,
    compileCommand: ["c3c", "compile", "-o", "/workspace/solution", "/workspace/solution.c3"],
    runCommand: ["/workspace/solution"],
  },
  vala: {
    language: "vala",
    displayName: "Vala",
    standard: `${JUDGE_TOOLCHAIN_VERSIONS.vala}`,
    extension: ".vala",
    dockerImage: "judge-vala:latest",
    compiler: `Vala ${JUDGE_TOOLCHAIN_VERSIONS.vala} (valac)`,
    compileCommand: ["valac", "-o", "/workspace/solution", "/workspace/solution.vala"],
    runCommand: ["/workspace/solution"],
  },
  nelua: {
    language: "nelua",
    displayName: "Nelua",
    standard: null,
    extension: ".nelua",
    dockerImage: "judge-nelua:latest",
    compiler: "Nelua",
    compileCommand: ["sh", "-c", "HOME=/tmp nelua -o /workspace/solution /workspace/solution.nelua"],
    runCommand: ["/workspace/solution"],
  },
  hare: {
    language: "hare",
    displayName: "Hare",
    standard: null,
    extension: ".ha",
    dockerImage: "judge-hare:latest",
    compiler: "Hare",
    compileCommand: ["sh", "-c", "HOME=/tmp HARECACHE=/tmp/hare hare build -o /workspace/solution /workspace/solution.ha"],
    runCommand: ["/workspace/solution"],
  },
  koka: {
    language: "koka",
    displayName: "Koka",
    standard: `${JUDGE_TOOLCHAIN_VERSIONS.koka}`,
    extension: ".kk",
    dockerImage: "judge-koka:latest",
    compiler: `Koka ${JUDGE_TOOLCHAIN_VERSIONS.koka}`,
    compileCommand: [
      "sh", "-c",
      "HOME=/tmp KOKA_HOME=/usr/local koka -O2 --outputdir=/tmp/koka-out -o /workspace/solution /workspace/solution.kk && chmod +x /workspace/solution",
    ],
    runCommand: ["/workspace/solution"],
  },
  lean: {
    language: "lean",
    displayName: "Lean 4",
    standard: `${JUDGE_TOOLCHAIN_VERSIONS.lean}`,
    extension: ".lean",
    dockerImage: "judge-lean:latest",
    compiler: `Lean ${JUDGE_TOOLCHAIN_VERSIONS.lean}`,
    compileCommand: null,
    runCommand: ["sh", "-c", "HOME=/tmp lean --run /workspace/solution.lean"],
  },
  picat: {
    language: "picat",
    displayName: "Picat",
    standard: `${JUDGE_TOOLCHAIN_VERSIONS.picat}`,
    extension: ".pi",
    dockerImage: "judge-picat:latest",
    compiler: null,
    compileCommand: null,
    runCommand: ["picat", "/workspace/solution.pi"],
  },
  mercury: {
    language: "mercury",
    displayName: "Mercury",
    standard: `${JUDGE_TOOLCHAIN_VERSIONS.mercury}`,
    extension: ".m",
    dockerImage: "judge-mercury:latest",
    compiler: `Melbourne Mercury Compiler ${JUDGE_TOOLCHAIN_VERSIONS.mercury}`,
    compileCommand: ["sh", "-c", "export HOME=/tmp && cd /workspace && mmc --make solution 2>&1"],
    runCommand: ["/workspace/solution"],
  },
  wat: {
    language: "wat",
    displayName: "WebAssembly",
    standard: "WAT",
    extension: ".wat",
    dockerImage: "judge-wat:latest",
    compiler: `wabt ${JUDGE_TOOLCHAIN_VERSIONS.wabt} / wasmtime ${JUDGE_TOOLCHAIN_VERSIONS.wasmtime}`,
    compileCommand: ["wat2wasm", "/workspace/solution.wat", "-o", "/workspace/solution.wasm"],
    runCommand: ["sh", "-c", "HOME=/tmp wasmtime /workspace/solution.wasm"],
  },
  purescript: {
    language: "purescript",
    displayName: "PureScript",
    standard: `${JUDGE_TOOLCHAIN_VERSIONS.purescript}`,
    extension: ".purs",
    dockerImage: "judge-purescript:latest",
    compiler: `PureScript ${JUDGE_TOOLCHAIN_VERSIONS.purescript} (purs)`,
    compileCommand: ["sh", "-c", "HOME=/tmp && cp -f /workspace/solution.purs /opt/purescript-project/src/Main.purs && cd /opt/purescript-project && spago build 2>&1"],
    runCommand: ["node", "-e", "require('/opt/purescript-project/output/Main/index.js').main()"],
  },
  modula2: {
    language: "modula2",
    displayName: "Modula-2",
    standard: "ISO",
    extension: ".mod",
    dockerImage: "judge-modula2:latest",
    compiler: `GCC gm2 ${JUDGE_TOOLCHAIN_VERSIONS.fortran}`,
    compileCommand: ["gm2", "-fiso", "-O2", "-o", "/workspace/solution", "/workspace/solution.mod"],
    runCommand: ["/workspace/solution"],
  },
  factor: {
    language: "factor",
    displayName: "Factor",
    standard: `${JUDGE_TOOLCHAIN_VERSIONS.factor}`,
    extension: ".factor",
    dockerImage: "judge-factor:latest",
    compiler: null,
    compileCommand: null,
    runCommand: ["sh", "-c", "HOME=/tmp FACTOR_HOME=/opt/factor /opt/factor/factor /workspace/solution.factor"],
  },
  spark: {
    language: "spark",
    displayName: "SPARK",
    standard: "Ada/SPARK 2014",
    extension: ".adb",
    dockerImage: "judge-ada:latest",
    compiler: `GNAT (GCC ${JUDGE_TOOLCHAIN_VERSIONS.gnat})`,
    compileCommand: ["gnatmake", "-O2", "-o", "/workspace/solution", "/workspace/solution.adb"],
    runCommand: ["/workspace/solution"],
  },
  minizinc: {
    language: "minizinc",
    displayName: "MiniZinc",
    standard: `${JUDGE_TOOLCHAIN_VERSIONS.minizinc}`,
    extension: ".mzn",
    dockerImage: "judge-minizinc:latest",
    compiler: null,
    compileCommand: null,
    runCommand: ["sh", "-c", "HOME=/tmp minizinc-judge /workspace/solution.mzn"],
  },
  curry: {
    language: "curry",
    displayName: "Curry",
    standard: `PAKCS ${JUDGE_TOOLCHAIN_VERSIONS.pakcs}`,
    extension: ".curry",
    dockerImage: "judge-curry:latest",
    compiler: `PAKCS ${JUDGE_TOOLCHAIN_VERSIONS.pakcs}`,
    compileCommand: ["sh", "-c", "export HOME=/tmp && cd /workspace && printf ':load solution\\n:save\\n:quit\\n' | pakcs 2>&1"],
    runCommand: ["/workspace/solution"],
  },
  clean: {
    language: "clean",
    displayName: "Clean",
    standard: `${JUDGE_TOOLCHAIN_VERSIONS.clean}`,
    extension: ".icl",
    dockerImage: "judge-clean:latest",
    compiler: `Clean ${JUDGE_TOOLCHAIN_VERSIONS.clean}`,
    compileCommand: [
      "sh", "-c",
      "export HOME=/tmp CLEAN_HOME=/opt/clean CLEANPATH=/opt/clean/StdEnv:/opt/clean/lib PATH=/opt/clean/bin:/opt/clean/exe:$PATH && mkdir -p /tmp/clean-artifacts && cd /workspace && cp solution.icl Solution.icl && clm -I /opt/clean/StdEnv -nt -nr Solution -o /workspace/solution 2>&1",
    ],
    runCommand: ["sh", "-c", "HOME=/tmp /workspace/solution"],
  },
  carp: {
    language: "carp",
    displayName: "Carp",
    standard: `${JUDGE_TOOLCHAIN_VERSIONS.carp}`,
    extension: ".carp",
    dockerImage: "judge-carp:latest",
    compiler: `Carp ${JUDGE_TOOLCHAIN_VERSIONS.carp}`,
    compileCommand: ["sh", "-c", "export HOME=/tmp CARP_DIR=/opt/carp && cd /workspace && carp -b solution.carp 2>&1"],
    runCommand: ["/workspace/out/solution"],
  },
  grain: {
    language: "grain",
    displayName: "Grain",
    standard: `${JUDGE_TOOLCHAIN_VERSIONS.grain}`,
    extension: ".gr",
    dockerImage: "judge-grain:latest",
    compiler: `Grain ${JUDGE_TOOLCHAIN_VERSIONS.grain}`,
    compileCommand: ["grain", "compile", "/workspace/solution.gr", "-o", "/workspace/solution.wasm"],
    runCommand: ["grain", "run", "/workspace/solution.wasm"],
  },
  pony: {
    language: "pony",
    displayName: "Pony",
    standard: `${JUDGE_TOOLCHAIN_VERSIONS.pony}`,
    extension: ".pony",
    dockerImage: "judge-pony:latest",
    compiler: `ponyc ${JUDGE_TOOLCHAIN_VERSIONS.pony}`,
    compileCommand: ["sh", "-c", "export HOME=/tmp && cd /workspace && mkdir -p build && cp solution.pony build/main.pony && cd build && ponyc -o /workspace --bin-name solution 2>&1"],
    runCommand: ["/workspace/solution"],
  },
  moonbit: {
    language: "moonbit",
    displayName: "MoonBit",
    standard: `${JUDGE_TOOLCHAIN_VERSIONS.moonbit}`,
    extension: ".mbt",
    dockerImage: "judge-moonbit:latest",
    compiler: `moon ${JUDGE_TOOLCHAIN_VERSIONS.moonbit}`,
    compileCommand: ["sh", "-c", "export HOME=/tmp MOON_HOME=/root/.moon && cp -r /opt/moonbit-project /tmp/moonbit-project && cp /workspace/solution.mbt /tmp/moonbit-project/main/main.mbt && cd /tmp/moonbit-project && moon build --target native 2>&1 && cp _build/native/debug/build/main/main.exe /workspace/solution"],
    runCommand: ["/workspace/solution"],
  },
  chapel: {
    language: "chapel",
    displayName: "Chapel",
    standard: `${JUDGE_TOOLCHAIN_VERSIONS.chapel}`,
    extension: ".chpl",
    dockerImage: "judge-chapel:latest",
    compiler: `chpl ${JUDGE_TOOLCHAIN_VERSIONS.chapel}`,
    compileCommand: ["chpl", "-o", "/workspace/solution", "/workspace/solution.chpl"],
    runCommand: ["/workspace/solution"],
  },
  idris2: {
    language: "idris2",
    displayName: "Idris 2",
    standard: `${JUDGE_TOOLCHAIN_VERSIONS.idris2}`,
    extension: ".idr",
    dockerImage: "judge-idris2:latest",
    compiler: `Idris 2 ${JUDGE_TOOLCHAIN_VERSIONS.idris2} (Chez Scheme)`,
    compileCommand: ["sh", "-c", "export HOME=/tmp && cd /workspace && idris2 solution.idr -o solution 2>&1"],
    runCommand: ["/workspace/build/exec/solution"],
  },
  rescript: {
    language: "rescript",
    displayName: "ReScript",
    standard: `${JUDGE_TOOLCHAIN_VERSIONS.rescript}`,
    extension: ".res",
    dockerImage: "judge-rescript:latest",
    compiler: `ReScript ${JUDGE_TOOLCHAIN_VERSIONS.rescript}`,
    compileCommand: ["sh", "-c", "cp -r /opt/rescript-project /tmp/rescript-project && cp /workspace/solution.res /tmp/rescript-project/src/Solution.res && cd /tmp/rescript-project && npx rescript 2>&1 && cp /tmp/rescript-project/src/Solution.res.js /workspace/solution.js"],
    runCommand: ["sh", "-c", "NODE_PATH=/opt/rescript-project/node_modules node /workspace/solution.js"],
  },
  elm: {
    language: "elm",
    displayName: "Elm",
    standard: `${JUDGE_TOOLCHAIN_VERSIONS.elm}`,
    extension: ".elm",
    dockerImage: "judge-elm:latest",
    compiler: `Elm ${JUDGE_TOOLCHAIN_VERSIONS.elm}`,
    compileCommand: ["sh", "-c", "export HOME=/tmp && cp -r /root/.elm /tmp/.elm && export ELM_HOME=/tmp/.elm && cp -r /opt/elm-project /tmp/elm-project && cp /workspace/solution.elm /tmp/elm-project/src/Main.elm && cd /tmp/elm-project && elm make src/Main.elm --optimize --output=/workspace/solution.js 2>&1 && cp /opt/elm-project/driver.js /workspace/driver.js"],
    runCommand: ["node", "/workspace/driver.js"],
  },
};

export const DEFAULT_JUDGE_LANGUAGES = Object.values(JUDGE_LANGUAGE_CONFIGS);

export function isJudgeLanguage(language: string): language is Language {
  return language in JUDGE_LANGUAGE_CONFIGS;
}

export function getJudgeLanguageDefinition(language: string) {
  return isJudgeLanguage(language) ? JUDGE_LANGUAGE_CONFIGS[language] : null;
}

/** Return a human-readable label such as "C++ (C++20)" or "Python". */
export function getLanguageDisplayLabel(language: string): string {
  const def = getJudgeLanguageDefinition(language);
  if (!def) return language;
  return def.standard ? `${def.displayName} (${def.standard})` : def.displayName;
}

function shellEscapeJudgeToken(token: string) {
  if (/^[A-Za-z0-9_@%+=:,./-]+$/.test(token)) {
    return token;
  }

  return `'${token.replace(/'/g, `'"'"'`)}'`;
}

export function serializeJudgeCommand(command: string[] | null | undefined) {
  if (!command || command.length === 0) {
    return null;
  }

  if (command[0] === "sh" && command[1] === "-c") {
    return command.slice(2).join(" ");
  }

  return command.map(shellEscapeJudgeToken).join(" ");
}

export function deserializeStoredJudgeCommand(command: string | null | undefined) {
  const trimmed = command?.trim();

  if (!trimmed) {
    return null;
  }

  const shellWrappedMatch = trimmed.match(/^sh\s+-c\s+([\s\S]+)$/);

  return ["sh", "-c", shellWrappedMatch ? shellWrappedMatch[1] : trimmed];
}
